### ISSUE TITLE
Dependencies of project

### ISSUE THREAD

**Issue by Tenzer** [thisbejim/Pyrebase#1]
I can see from the [commit history](https://github.com/thisbejim/Pyrebase/commit/48fbfeaf92d6f9415345c1ec8016d1ca4a20dfb8) that the `setup.py` file was part of this repository earlier, but was removed. What was the reason behind that?

Having neither `setup.py` or a `requirements.txt` in the project will make it more difficult for contributors to figure out which dependencies the project relies on, and which versions you may have pinned of those packages.

Would you consider adding at least one of the two files back in?

**Comment by thisbejim** [comment]
Thanks for your input Tenzer, there was no good reason for removing either files, I've added them both back to the project.

**Comment by Tenzer** [comment]
Thanks! The reason I noticed it, was because I would like to add a couple of extra features that I think you are missing: A `delete()` call and a `keys()` call - the latter basically being the same as the `all()` function, but with the [shallow](https://www.firebase.com/docs/rest/api/#section-param-shallow) parameter set.
I'll make a PR one of the following days on these.
