### ISSUE TITLE
Documentation on set method is confusing

### ISSUE THREAD

**Issue by ddeath** [thisbejim/Pyrebase#101]
Hi,

I was expecting that if I use code:

    db.child('users').set({'Mark': {mark`s attributes... }})

that it will create a new key Mark under the users, but it actually deletes all keys in users and then it adds Mark key...

It was a little bit confusing. Maybe you can add an example there what is the result of the action.

**Comment by thisbejim** [comment]
Thanks for bringing this up @ddeath, you are right that this action will just delete all users and is very confusing. The docs should be changed to something like:

```
db.child('users').child('Mark').set({mark`s attributes... })
```

**Comment by thisbejim** [comment]
This is resolved with https://github.com/thisbejim/Pyrebase/commit/042f55bbdf435aef7c23907ef3bb41f663d92b7b
