### ISSUE TITLE
Weird redirects

### ISSUE THREAD

**Issue by busla** [thisbejim/Pyrebase#102]
I´m getting these weird redirects in my logs all of the sudden.

```
[Thread-6:401 -  _make_request() ] - 2016-11-13 23:21:11,841:  "GET /test/ras1.json HTTP/1.1" 307 0
[Thread-6:805 -  _new_conn() ] - 2016-11-13 23:21:11,898:  Starting new HTTPS connection (1): s-usc1c-nss-118.firebaseio.com
```

These lines seem to be is coming from urllib3. Were not there before.

Anyone else experiencing this?

**Comment by thisbejim** [comment]
Is this during streaming?

**Comment by busla** [comment]
This is where I create the streams:

```python
        for subscriber in self.publisher.get_subscribers('update'):
            logger.info('Creating firebase stream for: {}'.format(subscriber.name))            
            data = db.child("test").child(subscriber.name).child(datetime.strftime(datetime.now(), self.datetime_format)).get().val()
            logger.info('Subscriber: {}'.format(subscriber))
            #logger.info('Data: {}'.format(data))
            self.parse_initial_data(data, subscriber.name)
            db.child('test').child(subscriber.name).stream(self.stream_handler, stream_id=subscriber.name)
```

**Comment by busla** [comment]
It happens after the stream() initialisation.

**Comment by thisbejim** [comment]
Are you using a service account?

**Comment by busla** [comment]
No authentication

**Comment by thisbejim** [comment]
So this is prob an caused by https://github.com/thisbejim/Pyrebase/commit/fad1ab754daa4c5239f2c805f4919f968c9cb265 which restarts streams every half hour to reauthenticate service accounts and avoid stale tokens (tokens expire after 1 hours).

**Comment by thisbejim** [comment]
If you are using no auth it will just restart the stream as normal.

**Comment by busla** [comment]
This happens on every restart of my app, where I should have a fresh token.

**Comment by thisbejim** [comment]
Oh I see, yeah that redirect is normal, Firebase maps your database url like ```https://databaseName.firebaseio.com``` to a url like ```s-usc1c-nss-1412.firebaseio.com``` when streaming, that's just how they do it. It actually caused a few problems for people using service accounts when streaming because the requests module strips Authentication headers on redirects, so we couldn't properly authenticate people when streaming and had to do some whacky workarounds to get auth to stick.

Not sure why these weren't in your logs before but yeah that is normal behaviour.

**Comment by busla** [comment]
Ok, thanks for clarifying this 👍 

I will start using authentication eventually so I´ll deal with the resetting when that time comes.

**Comment by thisbejim** [comment]
Awesome 😃
