### ISSUE TITLE
Unable to install Pyrebase inside pyvenv(Python3 Virtual Environment)

### ISSUE THREAD

**Issue by prashantkrsahu** [thisbejim/Pyrebase#104]
Hello,
I am unable to install Pyrebase inside [pyvenv](https://docs.python.org/3/library/venv.html).
When I try `pip install pyrebase `i got the following error.

> unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     

When I try this on local machine (without pyvenv) it works.
I am not sure what the problem is, but I think some dependency library is missing. I would really appreciate if anyone have any solutions.

**Comment by ddeath** [comment]
what is your version of python in pyvenv?

I am using [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/) and I do not have a problem at all...

**Comment by thisbejim** [comment]
Any luck with this @prashantkrsahu, I think this might not be a Pyrebase issue...

**Comment by busla** [comment]
@prashantkrsahu looks like build-essential and python-dev is missing.

`sudo apt-get install build-essential python-dev`
