### ISSUE TITLE
[Question] Re-Authenticating

### ISSUE THREAD

**Issue by thedanisme** [thisbejim/Pyrebase#116]
```
Make sure these boxes are checked before submitting your issue:

[3.5.2] Check that your version of Python is 3.4+
[3.0.25] Check that you are on the newest version of Pyrebase
[Enabled] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.
```

I apologize if this is not a great place for this, but there doesn't seem to be any other way to get development help with Pyrebase.

I am new-ish to python and programming in general.  I have developed a small Discord bot for my World of Warcraft guild that uses Firebase & Pyrebase for a database.  The bot can authenticate into Firebase just fine when it is started and for the first hour it's up, everything works amazing.  The trouble starts when the token expires, and I try to reauthenticate.  I'm not 100% how this would be done and my Google searches have been fruitless.

The latest version of my reauthenticate function was:
```
async def refreshAuth():
    auth = firebase.auth()
    user = auth.sign_in_with_email_and_password(secrets.EMAIL, secrets.PASSWORD)
    user = auth.refresh(user['refreshToken'])
```

Which, obviously to those more knowledgeable than me, did not work.  I have tried several combinations of this and just calling `user = auth.refresh(user['refreshToken'])` did not help either.

I initialize pyrebase using:
```
#firebase init
firebase = pyrebase.initialize_app(secrets.config)
db = firebase.database()
auth = firebase.auth()
user = auth.sign_in_with_email_and_password(secrets.EMAIL, secrets.PASSWORD)
token = user['idToken']
```

My firebase config is:
```
config = {
    "apiKey": "API_key_here",
    "authDomain": "link_here.firebaseapp.com",
    "databaseURL": "https://link_here.firebaseio.com",
    "storageBucket": "link_here.appspot.com",
    "serviceAccount": "link_to_json_here.json"
}
```

I have been reading the documentation and even looking into `pyrebase.py` and cannot come up with an answer that works without having to restart my python program to get a new authentication.

**Comment by thedanisme** [comment]
I'm not going to explore this further.

**Comment by thisbejim** [comment]
Hey @thedanisme, thanks for opening this issue! I agree that the experience for refreshing user tokens is terrible at the moment. 

This is unlikely to change in the short term (I maintain Pyrebase for fun and don't always have the time to give it the attention it deserves) but I definitely think that refreshing tokens should be something that Pyrebase does internally.

**Comment by thisbejim** [comment]
Oh wait so you are using Pyrebase for a bot? Check out the Pyrebase documentation for using a service account (rather than email + password comba) which does automatically handle refreshing tokens for you.
