### ISSUE TITLE
get() on dictionaries with sub-dictionaries fail

### ISSUE THREAD

**Issue by Tenzer** [thisbejim/Pyrebase#12]
During a bit of testing, I found out with a Firebase structure such as:

```json
{
    "test": {
        "bool": true,
        "number": 123,
        "string": "test"
    }
}
```

then `Firebase.query("test").get()` correctly returns `{'bool': True, 'number': 123, 'string': 'test'}`. But if the data in Firebase instead looks like this:

```json
{
    "test": {
        "bool": true,
        "number": 123,
        "string": "test",
        "sub": {
            "string": "test"
        }
    }
}
```

and you do the same query, then it will fail with this error message:

    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "path/to/virtualenv/lib/python3.4/site-packages/pyrebase/pyrebase.py", line 99, in get
        request_dict[i]["key"] = i
    TypeError: 'bool' object does not support item assignment

I'm not too much a fan of all the reformatting of the output going on in the current `get()` method. It is of course needed if you want a sorted output, due to dictionaries in Python not being ordered (unless you use a [OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict)), but it should at least be able to handle the simpler cases before the more advanced cases, in my opinion.

**Comment by thisbejim** [comment]
Should be solved with f7dadcf1ab1559c86bcba37c97d3037de0c0d495
