### ISSUE TITLE
Support for locking a transaction when doing .push()

### ISSUE THREAD

**Issue by aligajani** [thisbejim/Pyrebase#120]
I don't want anyone to write to a node until I push my data successfully. Is this possible?

**Comment by thisbejim** [comment]
Hi @aligajani, thanks for the question! This is not possible at the moment unfortunately, Firebase doesn't offer this capability through the REST API. I wish it did though. There are be some [creative ways to come up with similar functionality](https://github.com/thisbejim/Pyrebase/issues/55) though.
