### ISSUE TITLE
Does the initial bulk stream block the individial message streams?

### ISSUE THREAD

**Issue by aligajani** [thisbejim/Pyrebase#124]
I want to know if the initial bulk stream blocks the individual message streams. Say I restart my handler, and there are a 1m messages in total, will the 1m+1th message be blocked while waiting for the 1m initial bulk stream to download, or is this not the issue?

**Comment by thisbejim** [comment]
Hi @aligajani, I found an interesting thread on this topic that [you might like to read](https://groups.google.com/forum/#!topic/firebase-talk/lflNSiKmMhM).

**Comment by aligajani** [comment]
Useful.
