### ISSUE TITLE
Multi-Location Updates repalce all children of updated node.

### ISSUE THREAD

**Issue by Ragnt** [thisbejim/Pyrebase#126]
I think I found an issue (or am not understanding your documentation) where multi-location updates is replacing ALL children under a node instead of replacing just the updated ones. 

IE: It's acting like set, and "setting" the parent node to the values listed.

Example database:
```
{
	"Parent": {
		"key1": node1,
		"key2": {
			"key01": node01,
			"key02": node02,
		}
		"key3": node3,
		"key4": node4
	}
}
```

If I attempt to use multi-location update to change the value of just Key1 and the Values under key02 using:

```
data = {
	"Parent/": {
		"key1": changedNode,
		"key2": {
			"key01": changedNode,
			"key02": changedNode
		}
	}
}
db.update(data)
```

It replaces all the values (IE< removing unchanged values). The end result would be:

```
{
	"Parent": {
		"key1": changedNode,
		"key2": {
			"key01": changedNode,
			"key02": changedNode,
		}
	}
}
```

Which is obviously not what I want. Could I be using this incorrectly? The linked blog post states that update will specifically not change the values that are not included in the update.

To clarify why I would use this methode (despite both being under the same parent node):

Previously I made these database changes by using set on each child individually. However, at times the second set would throw some crazy errors where it would write to completely random places inside of the database and return a 500, presumably because the writes happened back-to-back. To alleviate this, I decided to use update and therefore make changes in one go (rather then delay my second set).

**Comment by Ragnt** [comment]
This has been solved for me, by instead using:

`db.child("parent1").child("parent2").update(data)`

Instead of using just db.update(data) and referencing the location to the update within the data object itself as such:

```
{
	"Parent1/paretn2": {
		"key1": changedNode,
		"key2": {
			"key01": changedNode,
			"key02": changedNode,
		}
	}
}
```

**Comment by thisbejim** [comment]
Nice work solving this @Ragnt!
