### ISSUE TITLE
Python 2.6

### ISSUE THREAD

**Issue by JimJty** [thisbejim/Pyrebase#127]
Do you know what would be involved to get this working for Python 2.6? From the testing I did, it appears to be working. Do you know of any specific issues? I'm looking for an updated library from https://github.com/ozgur/python-firebase.

**Comment by thisbejim** [comment]
Hi @JimJty, thanks for the question!

I'm not exactly sure what doesn't work, I think there might be some issues with streaming and probably a few other things. Feel free to fork and make changes if you run into any issues, but in general Pyrebase doesn't support python 2.
