### ISSUE TITLE
Downloading Image yields AttributeError

### ISSUE THREAD

**Issue by ericjsalazar** [thisbejim/Pyrebase#128]
Using python 3.6.0
Using latest pyrebase
Using config with following:

```
config = {
  "apiKey": "xxxxxxxxx",
  "authDomain": "xxxxxxxx.firebaseapp.com",
  "databaseURL": "https://xxxxxx.firebaseio.com/",
  "storageBucket": "xxxxxxxxx.appspot.com",
  "serviceAccount": "/Users/xxxxx"
}
# Initialize firebase connection
firebase = pyrebase.initialize_app(config)

# Authorization
auth = firebase.auth()
db = firebase.database()
storage = firebase.storage()
storage.child("Incomplete Scans/18 January 2017/of5IU1fgR7NFa1ffcpc2rg5UemO2").download("OK.jpg")
```
Error:
 blob.download_to_filename(filename)
AttributeError: 'NoneType' object has no attribute 'download_to_filename'

Any ideas what I need to change or if this is a bug? Thank you!

**Comment by ericjsalazar** [comment]
I've found a solution:

When downloading from a specific path, using successive .child("") nodes instead of just one .child("x/y/z") yields the correct functionality. 

Example:
`storage.child("Incomplete Scans/18 January 2017/of5IU1fgR7NFa1ffcpc2rg5UemO2").download("OK.jpg")` 
^ breaks it

`storage.child("Incomplete Scans").child(18 January 2017").child("of5IU1fgR7NFa1ffcpc2rg5UemO2").download("OK.jpg")`
^ works

Thanks! This can be marked as closed.

Sidenote: in config block, if serviceAccount is labeled as "credentials" this error is not thrown, however the download doesn't do anything.

**Comment by raionas** [comment]
Hi, I'm sort of running into the same issue while trying to download a user-generated (not an image rather a .csv) and I've also tried to break using the successive child() but to I can't seem to get it worked out. Any inputs would be great. Thanks!

# storage service reference
storage = firebase.storage()

# check storage information
storage.child('/Files')

# Create a pointer to the file in the cloud
storage.child("analyseit-88ed7.appspot.com")

storage.child("/Files").child("retail-ms.csv").download("goods.csv")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-274-5c4dad3f45aa> in <module>()
----> 1 storage.child("/Files").child("retail-ms.csv").download("goods.csv")

~/anaconda3/lib/python3.6/site-packages/pyrebase/pyrebase.py in download(self, filename, token)
    419         if self.credentials:
    420             blob = self.bucket.get_blob(path)
--> 421             blob.download_to_filename(filename)
    422         else:
    423             r = requests.get(url, stream=True)

**AttributeError: 'NoneType' object has no attribute 'download_to_filename'**
