### ISSUE TITLE
Provide output in an OrderedDict to keep sorting

### ISSUE THREAD

**Issue by Tenzer** [thisbejim/Pyrebase#13]
Carrying on from #12, I think it would make sense to always use an OrderedDict everywhere in Pyrebase. Firebase use the ordering of the elements in the JSON response as a response to the sorting requested in the request, but the standard Python dictionary does not keep the ordering, which means we currently implement our own sorting on top of what Firebase does.

If we instead decode the JSON ourselves, using the `object_pairs_hook` kwarg, we can supply that with an OrderedDict as shown [here](http://stackoverflow.com/a/6921760/878291), which will keep the ordering, and thus require less work on our end since we don't need to sort the elements again.

I think the only handling we need of the response from Firebase then would be the following:

1. Is the JSON decoded response something else than a dict/OrderedDict? If yes, then simply return it.
2. Are we doing a `shallow` request? If yes, then only return the keys of the dictionary.

What are your thoughts on this?

**Comment by thisbejim** [comment]
The problem is that the JSON results themselves aren't ordered at all, from the [REST docs we find](https://www.firebase.com/docs/rest/guide/retrieving-data.html#section-rest-filtering): "When using the REST API, the filtered results are returned in an undefined order since JSON interpreters don't enforce any ordering. If the order of your data is important you should sort the results in your application after they are returned from Firebase."

So unfortunately we have to implement some sort of ordering on our end, which sucks because at the moment it is messy! I like the idea of using an OrderedDict though so will have a mull over that.

**Comment by Tenzer** [comment]
Bugger, I was actually just about to do a bit on testing of that. You could argue that Pyrebase only should take care of the communication with Firebase, and it would then be up to the people using Pyrebase to sort it on their end if needed. The sorting parameters should still be sent to Firebase though, as it can be used to limit the output you get from them.

**Comment by Tenzer** [comment]
For my test I used a structure like this, with an index on `param`:
```json
{
  "test": {
    "-K4-Sig7Z9hv6o82zxwZ": {
      "param": 3
    },
    "-K4-SjVqW_l8olgTfLJx": {
      "param": 2
    },
    "-K4-SkBvJdYpOsTc81Dz": {
      "param": 1
    }
  }
}
```

This was the output from `curl`:
```
$ curl 'https://<id>.firebaseio.com/test.json?print=pretty'
{
  "-K4-Sig7Z9hv6o82zxwZ" : {
    "param" : 3
  },
  "-K4-SjVqW_l8olgTfLJx" : {
    "param" : 2
  },
  "-K4-SkBvJdYpOsTc81Dz" : {
    "param" : 1
  }
}
```
```
$ curl 'https://falconbuildtest.firebaseio.com/test.json?orderBy="$key"&print=pretty'
{
  "-K4-Sig7Z9hv6o82zxwZ" : {
    "param" : 3
  },
  "-K4-SjVqW_l8olgTfLJx" : {
    "param" : 2
  },
  "-K4-SkBvJdYpOsTc81Dz" : {
    "param" : 1
  }
}
```
```
$ curl 'https://<id>.firebaseio.com/test.json?orderBy="param"&print=pretty'
{
  "-K4-Sig7Z9hv6o82zxwZ" : {
    "param" : 3
  },
  "-K4-SjVqW_l8olgTfLJx" : {
    "param" : 2
  },
  "-K4-SkBvJdYpOsTc81Dz" : {
    "param" : 1
  }
}
```
There's no difference on the order of the data we get back from Firebase, unfortunately :(

**Comment by thisbejim** [comment]
Yeah it is definitely a hassle! 

I do think pyrebase should offer sorting so it can be a full, useful solution, just requires a bit of a rethink to make sure it handles most cases.

**Comment by thisbejim** [comment]
Pretty much sorted on this front with: https://github.com/thisbejim/Pyrebase/commit/d4a83b887d9b26634d9f218caa35903220926dc2
