### ISSUE TITLE
How to access stream data from outside?

### ISSUE THREAD

**Issue by alexanderwhatley** [thisbejim/Pyrebase#130]
Right now, the streaming API doesn't give an example of how the streaming function could return the data to an outside source. For example, if you wanted to access all of the streaming data up to the current point, could you do something like this:

```
def stream_handler(message):
    yield message

my_stream = db.child("posts").stream(stream_handler)

yield from my_stream?
```

**Comment by aligajani** [comment]
What you mean 'outside source'?

**Comment by alexanderwhatley** [comment]
Actually never mind I figured it out.

**Comment by vmanikes** [comment]
Can you let me know how you did that?
