### ISSUE TITLE
A request returns None instead of key

### ISSUE THREAD

**Issue by JaySunSyn** [thisbejim/Pyrebase#131]
Hi,

many thanks for creating Pyrebase! v3.0.27

I've got an issue with below database, the **channel** key returns None.

**Database**

https://etest-3208f.firebaseio.com/ (not secured, ready to test)

![image](https://cloud.githubusercontent.com/assets/5872432/22202734/c864d394-e169-11e6-9719-e76a78e24975.png)

**Issue**
Request

```
import pyrebase

FIREBASE_CONFIG = {
  'apiKey': '',
  'authDomain': '',
  'storageBucket': '',
  'databaseURL': 'https://etest-3208f.firebaseio.com/',
  'serviceAccount': ''
}

f = pyrebase.initialize_app(FIREBASE_CONFIG)
db = f.database()

db.child("users").child("4").child("notifications").child("inbox").get().val()

```

*Result*

```
OrderedDict([('channels',
              [None,
               {'-KbA2BY0e4A06UPBOvvW': {'created_at': '17-01-23T11:18.580984',
                 'read': False,
                 'sender_avatar': 'https://abc.com/media/images/client_avatars/51ee78d5-e85.png',
                 'sender_name': 'Jess',
                 'type': 'inbox',
                 'url': '/dashboard/visits/1/',
                 'visit_info': '17-02-03T10:00:00'}}])])
```

*Expected*
The channel key instead of None.

**Comment by thisbejim** [comment]
Hi @JaySunSyn, thanks for the question! 

Firebase sees keys in numerical order like 1, 2, 3, 4 etc as an array and so it an array item without a key. Try using a random key similar in randomness to `-KbA2BY0e4A06UPBOvvW` for the channel key and see if that makes a difference.

**Comment by JaySunSyn** [comment]
Thank you @thisbejim, worked fine!
