### ISSUE TITLE
Dict or Str on stream

### ISSUE THREAD

**Issue by veled** [thisbejim/Pyrebase#137]
Hi and thanks for this library,

I'm trying to stream some data. And as I can see if data exist before start stream it's a dict but if it exist or update while the stream is running its a str object. Can it always be a dict or str?
```

def stream_handler(post):
	data = (post["data"])
	key = (post["path"])

	if(data != None):
		TypeData = type(data)
		print(TypeData)

```

Output

> List _____________________ List
> <class 'dict'>
> <class 'str'>
>

**Comment by thisbejim** [comment]
Hi @veles, thanks for the question! Would you be able to provide an example of the data stored in firebase that you are trying to stream?
