### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by harpangell7** [thisbejim/Pyrebase#139]
Hey man I really love your wrapper! However I'm stuck... I have a template that has:

    <input type="file" name="test">

And in my view I have:

    filename = request.FILES['test']
    config = {
    "apiKey": "APiKey",
    "authDomain": "wogusodlqkqh.firebaseapp.com",
    "databaseURL": "https://wogusodlqkqh.firebaseio.com",
    "storageBucket": "wogusodlqkqh.appspot.com"
    }
    firebase = pyrebase.initialize_app(config)
    storage = firebase.storage()

Here is where I'm confused... I've tried a combination of different options but I cant seem to figure storage out? 
    storage.child(filename).put("DCIM/"+filename, user['idToken'])

Can you please help me out? I have already set up authorization, and the database, this is just really stumping me. 

Sincerely,

Denis Angell

**Comment by harpangell7** [comment]
Can anyone help me

**Comment by vimalgopal** [comment]
what exactly is the problem

**Comment by harpangell7** [comment]
I receive an error, "message": "Invalid HTTP method/URL pair.". I believe I have the most recent version of pyrebase. How can I check?

**Comment by vimalgopal** [comment]
https://github.com/thisbejim/Pyrebase/issues/79 check the issue , i think upgrading pyrebase might work ,just reinstall the whole thing .:D

**Comment by thisbejim** [comment]
Hi @harpangrll7, thank you for checking out Pyrebase and opening this issue!

Did you have any luck upgrading your installation as recommended by @vimalgopal?

**Comment by Gigarion** [comment]
I'm having the same problem, see attached error message.  Any help would be much appreciated, thanks in advance.  Tried reinstalling as suggested, no change

Traceback (most recent call last):
  File "DatabaseManager.py", line 56, in <module>
    dbm.store(None)
  File "DatabaseManager.py", line 48, in store
    self._store.child("Maps/").put("__init__.py",self._currUser['idToken'])
  File "C:\Users\Gig\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyrebase\pyrebase.py", line 396, in put
    raise_detailed_error(request_object)
  File "C:\Users\Gig\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyrebase\pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://firebasestorage.googleapis.com/v0/b/gs://location.appspot.com/o?name=Maps/] {
  "error": {
    "code": 400,
    "message": "Invalid HTTP method/URL pair."
  }
}


It looks perhaps like the url isn't formed right?

**Comment by harpangell7** [comment]
I'm still getting this error?

Here is my code:
sdb = firebase.storage()
user = auth.refresh(user['refreshToken'])
media = request.FILES['file']
print(media) # this is 'bronze_single.png'
result_storage = sdb.child('images/test.png').put(media, token=user['idToken'])

Are there settings in firebase that I need to update??

**Comment by harpangell7** [comment]
Ugh so I figured it out!! 

FOR THE BUCKET,
