### ISSUE TITLE
How to close stream by `stream_id`?

### ISSUE THREAD

**Issue by ukjin1192** [thisbejim/Pyrebase#144]
Thank you for maintaining this useful library :)

On documentation, we can specify `stream_id` to each stream like below.

~~~~
my_stream = db.child("posts").stream(stream_handler, stream_id="new_posts")
~~~~

Is it available to close the stream with matching `stream_id`?

**Comment by thisbejim** [comment]
Hi @ukjin1192, thanks for the question!

You can only close streams from your stream reference, e.g. my_stream so just name it accordingly like user_stream or like_stream and then call the close method on that.
