### ISSUE TITLE
Unable to install pyrebase 

### ISSUE THREAD

**Issue by thomasyoung-audet** [thisbejim/Pyrebase#145]
Hi, 
I am trying to install pyrebase on fedora and run into this error on installation. 

gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLTC_NO_ASM -Isrc/ -I/home/tyoung-audet/Documents/git_repos/lynkup/flask/include -I/usr/include/python3.5m -c src/MD2.c -o build/temp.linux-x86_64-3.5/src/MD2.o
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

Command "/home/tyoung-audet/Documents/git_repos/lynkup/flask/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pycharm-packaging/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4f39s7r9-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/tyoung-audet/Documents/git_repos/lynkup/flask/include/site/python3.5/pycryptodome" failed with error code 1 in /tmp/pycharm-packaging/pycryptodome/

Don't know what to do, 
Thanks for any info.

**Comment by kirubakaran** [comment]
@thomasyoung-audet Could you try:
```
sudo dnf install redhat-rpm-config
```

Source: https://bugs.launchpad.net/openstack-gate/+bug/1424582

**Comment by ashk-sonkar** [comment]
having similar issue

Command "C:\Users\hp\PycharmProjects\CheckPyrebase\venv\Scripts\python.exe -u -
c "import setuptools, tokenize;__file__='C:\\Users\\hp\\AppData\\Local\\Temp\\p
ip-install-wc189nef\\pycryptodome\\setup.py';f=getattr(tokenize, 'open', open)(
__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __fi
le__, 'exec'))" install --record C:\Users\hp\AppData\Local\Temp\pip-record-5qmg
n_hp\install-record.txt --single-version-externally-managed --compile --install
-headers C:\Users\hp\PycharmProjects\CheckPyrebase\venv\include\site\python3.7\
pycryptodome" failed with error code 1 in C:\Users\hp\AppData\Local\Temp\pip-in
stall-wc189nef\pycryptodome\

need help!

**Comment by Romesh99** [comment]
having issue 
-----------------------
Command ""C:\Users\Somesh\Desktop\python 1\django\venv\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Somesh\\AppData\\Local\\Temp\\pip-install-bqkms4hl\\p
ycryptodome\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Somesh
\AppData\Local\Temp\pip-record-667dc_pv\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\Somesh\Desktop\python 1\django\venv\include\site\py
thon3.8\pycryptodome"" failed with error code 1 in C:\Users\Somesh\AppData\Local\Temp\pip-install-bqkms4hl\pycryptodome\

plz help!
