### ISSUE TITLE
Cant kill the program with the streaming example

### ISSUE THREAD

**Issue by AbhayKD** [thisbejim/Pyrebase#149]
i cant get my way around this. I'm trying to get the streaming of pyrebase working and i have written he following program for that. The issue i'm facing is that i cant kill the program ofr exit the program with any keyboard interrupt or anything. I'm running the program on raspbian jessie and as a final solution i've to kill the putty session everytime to exit the program. pls help! 

import pyrebase

config = {
#Removed config just for security purpose
}

firebase = pyrebase.initialize_app(config)
db = firebase.database()

#path = db.child("Servo").child("Switch")

def stream_handler(message):
    print(message["data"])

if __name__ == "__main__":
    try:
        db.child("Servo").child("Switch").stream(stream_handler)
    except KeyboardInterrupt:
        os._exit()

**Comment by thisbejim** [comment]
What version of python are you using?

**Comment by AbhayKD** [comment]
python 2.7

**Comment by thisbejim** [comment]
Only python 3 is supported, make sure to check out the docs :)
