### ISSUE TITLE
Getting UID For User

### ISSUE THREAD

**Issue by justinackermann** [thisbejim/Pyrebase#161]
Maybe I am overlooking this in the documentation, but is there anyway to get the Users UID like you would in iOS (for example) so that you can write to the database at the same location under users. 

Using the id token you aren't able to do this as this will change every time you have to refresh the user token. 

Again maybe I am overlooking this but I can't find how to do this! 

Thanks! :)

**Comment by justinackermann** [comment]
Solved this myself.

After looking through the Pyrebase.py if you dump the auth data for a user, the UID assigned by Firebase will be the user['localId']

:)

**Comment by xaiyeon** [comment]
Hi, could you explain your solution a bit more? I tried look at the Pyrebase.py and did see the class, but I don't really understand what you mean by dump, as in the json file or?

I tried to just print the uid by: fireb_user = login with email
print(fireb_user['uid']) 

Are you still around? Thanks in advance...

**Comment by BenDurmishllari** [comment]
Is any way to pass on the system which user is log in? as the LoginManager act with the SQLAlchemy and relation databases?
