### ISSUE TITLE
gcloud.exceptions.NotFound: 404 Not Found on Storage Download

### ISSUE THREAD

**Issue by ericjsalazar** [thisbejim/Pyrebase#165]
Using python 3.6.0
Using latest pyrebase
Had successfully downloaded image (January)

Greetings, 
I'm getting a "gcloud.exceptions.NotFound: 404 Not Found" when calling download on storage objects. My current setup:

```
config = {
  "apiKey": "key #####",
  "authDomain": "xxx.firebaseapp.com",
  "databaseURL": "https://xxx.firebaseio.com/",
  "storageBucket": "gs://xxxx.appspot.com/",
  "serviceAccount": "/path/to/json"
}

firebase = pyrebase.initialize_app(config)
storage = firebase.storage()

storage.child("BucketName").child("17 04 2017 17:16:02").child("test_image").download("test_image.jpeg")
```

Any ideas? Thanks

EDIT: Yes the bucket exists. This exact code used to work in January.

**Comment by anurag0022** [comment]
remove gs:// from storage storageBucket

**Comment by acharyabidhan** [comment]
> remove gs:// from storage storageBucket

it worked :)
