### ISSUE TITLE
I need some help with the database.get() function

### ISSUE THREAD

**Issue by RedaBitar** [thisbejim/Pyrebase#172]
This is what I have so far:
```python
firebase = py.initialize_app(config)

auth = firebase.auth()
user = auth.sign_in_with_email_and_password(email, pass)

db = firebase.database()

users = db.child("users").get()
```

The user is an "owner" in the firebase console, however, when I call the get function, it says permission denied, unauthorized for the given URL. I can imagine that there is something missing in the get() call, I know that I need to provide some user info in the call, but I don't know what and how I should include it.

Can anyone help with this? Thanks in advance

**Comment by wstejka** [comment]
Hi RedaBitar,

There are two aspects you must take into consideration. First are the DB rules which you have applied in firebase . To check it out login on firebase console and then check DataBase -> Rules section. More info you can find here: 
https://firebase.google.com/docs/reference/security/database/

The second thing is related to the first one. If there are some more specific rules but your user is allowed for reading from /users node you must provide idToken to method.
It is really good documented but for your convenience I put it all together:

		firebase = pyrebase.initialize_app(config)
		###### AUTHENTICATION ############
		# Get a reference to the auth service
		auth = firebase.auth()

		# Log the user in
		user = auth.sign_in_with_email_and_password("login", "password")
		# Refresh token as it can expire after 1 hour
		user = auth.refresh(user['refreshToken'])
		# now we have a fresh token
		userIdToken = user['idToken']

		######## DATABASE #####################
		# Get a reference to the database service
		db = firebase.database()
                users = db.child("users").get(userIdToken)
 
hope it helps

**Comment by Manuel83** [comment]
It solved my issue. I was not aware that I have to provide the user Id Token to the get method.
I would recommend to update the README.md with this example
