### ISSUE TITLE
"dict" with numeric keys return strange list if keys do not increase by unity

### ISSUE THREAD

**Issue by lepmik** [thisbejim/Pyrebase#174]
Example

```python
value = {'1': 'df', '2': 'd', '5': 's'}
db.child('/path').set(value, user["idToken"])

db.child('/path').get(user["idToken"]).val()
[None, 'df', 'd', None, None, 's']
```

**Comment by thisbejim** [comment]
Hi @lepmik, thanks for dropping by!

Firebase does this funny thing where if you store a dict using numerical values for keys it will consider that data to be an array. So here we can see that the stored dict has no key for 0, 3, or 4, which maps to the index in the returned array, resulting in the None values in your example. 

I recommend using non-numerical keys when storing data that you don't want returned as an array.

**Comment by lepmik** [comment]
Ok, thank you for clearing that up 😀

4. jun. 2017 14.04 skrev "James Childs-Maidment" <notifications@github.com>:

**Comment by thisbejim** [comment]
No prob, anytime! 😀
