### ISSUE TITLE
Big chunk of old data on first stream recieve

### ISSUE THREAD

**Issue by giladondon** [thisbejim/Pyrebase#176]
So basically as the title says I run the following:
```
`samples_queue = {}


def stream_handler(message):
    if message["event"] == "patch":
        for key, value in message["data"].iteritems():
            samples_queue[key] = value
        print message["data"]
        # samples_queue[message["data"].key()] = message["data"].val()
        print samples_queue

my_stream = db.child("users").child("giladondon").child("keys").stream(stream_handler)`
```

The first chunk of data takes a few good minutes to get here, after that it's all fine. Also the first chunk of data is old and has been in the database before I started to stream.

**Comment by thisbejim** [comment]
Hi @giladondon, thanks for opening this issue!

Unfortunately this is something implemented by Firebase, whenever you open a stream they send all the existing data first and then send updates as they happen. I agree that it can be annoying but it is not something that can be fixed in Pyrebase.
