### ISSUE TITLE
How to get a ping/ notification when some change occurs in any key

### ISSUE THREAD

**Issue by harshil2712** [thisbejim/Pyrebase#182]
Q:
I am creating a python based code for Raspberry Pi for interconnected Pi's. 
Is there any way in pyrebase by which I can get a notification or some sort of ping whenever an entry is made into some key. For example, when a new mac address gets added to a key as value, some functions gets called. This should happen even when the notification receiving is not active on firebase cloud.
Please suggest some way to do this by python or is this possible by using firebase functions?

Make sure these boxes are checked before submitting your issue:

[] Check that your version of Python is 3.4+
[] Check that you are on the newest version of Pyrebase
[] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

**Comment by mcarrilloco** [comment]
Hi. I don't know if I fully understand your question, but I think what you might be looking at is the `stream` function in this library: https://github.com/thisbejim/Pyrebase#streaming. This requires that your code maintains a long live connection to Firebase and Firebase notifies the stream when changes are done to certain keys. If this is not a possibility, you could take a look at Firebase Cloud Functions https://firebase.google.com/docs/functions/; however, this is outside Pyrebase. Hope it helps.

**Comment by harshil2712** [comment]
Thanx Mcarrilloco,
I have not yet tried the Firebase Cloud Functions but I still have a doubt regarding the stream function in Pyrebase library. I used it in my code but it is returning the whole key and it,s values and not just the occurred change. Also, it requires mentioning the key in which I want to detect if a change has occurred. Instead, I want to get the change whenever a change occurs in any part of the whole database.

Please, do let me know if this is possible via python or I have to use Firebase functions.

**Comment by mcarrilloco** [comment]
When you start a stream, the first event you will received is the current state of the tree relative to the subscribed path. This is the expected functionality. Further events will reflect changes in that subtree.

I guess you could subscribe to the whole tree so you get changes that happen all over the database. Keep in mind that if the database is big, then you will start to experience delays when downloading the whole tree at first.

Pyrebase is, in essence, a wrapper around Firebase Rest API. So you can check the Firebase docs to see what's possible and what's not from their docs too. The relevant section for streaming is: https://firebase.google.com/docs/reference/rest/database/#section-streaming
