### ISSUE TITLE
Is there anyway to get the "Download Url" ?

### ISSUE THREAD

**Issue by tapuhi** [thisbejim/Pyrebase#183]
How can I get the Download Url of a file in firebase storage. The get_url is not good as other users can't donwload it unless I am missing something.

**Comment by tapuhi** [comment]
I found it, the answer to put (a file to storage) is a json which includes the download token.

**Comment by ubihacks** [comment]
how you get the right token

**Comment by ubihacks** [comment]
How you get the rite Url Download Token @tapuhi

**Comment by shadrackkip** [comment]
db = firebase.database()
storage = firebase.storage()

imgurl=storage.child("1.jpg").put("1.jpg")
img_url=storage.child("1.jpg").get_url(imgurl['downloadTokens'])

print(img_url)

**Comment by wmustafaAwad** [comment]
@shadrackkip  answer guided me, however, the syntax seems to have changed to be:

```
imgurl = storage.child("1.jpg").put("1.jpg",user['idToken'])    #Notice that you now have to supply the user['idToken']. Othewise imgurl will be a NoneType object
img_url = storage.child("1.jpg").get_url(imgurl['downloadTokens'])  
```
Where the user variable is retrieved for a service account using `auth.sign_in_with_email_and_password(email, password)
`
