### ISSUE TITLE
SOLVED PLEASE CLOSE: Problems loading nested dicts with Pyrebase?

### ISSUE THREAD

**Issue by evaristoc** [thisbejim/Pyrebase#185]
#Hi!

Trying to push nested dicts using Pyrebase unsuccessfully. My data structure should be like the following:
```
ids
  |
  --- record1
                 |
                 --- attribute1
                 |
                 --- attribute2
                 |
                 --- dictofattributes
                                            |
                                            --- nestedattribute1
                                            |
                                            --- nestedattribute2
  
```
That is what I present to pyrebase as data format, called `dbdata`. Be aware that the whole data structure is presented to the Pyrebase wrapper as a Python dict, where `dictofattributes` is a nested dict.

What I do to push the data into Pyrebase is:
```
db.child("id").push(dbdata, user['idToken'])
```
If I try the nested dict, I get the following error:
```
Invalid data; couldn't parse JSON object, array, or value.
```

I have tried several things including converting the nested dict into a json file and then reconverting it into a dict before pushing, assuming it is a format problem. 

Those solutions haven't worked. However if I pass the nested dict as a list of nested lists instead, it passes without conflict.

**EDIT**: forgot to mention that I am generating the naming and values of the nested dict dynamically. It seems not to be a problem if I explicitly assign a hard-coded dict to `dictofattributes`.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Make sure these boxes are checked before submitting your issue:

[x] Check that your version of Python is 3.4+
[x] Check that you are on the newest version of Pyrebase
[x] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

**Comment by evaristoc** [comment]
A format issue: some keys of dict embedded dicts had dots.

**Comment by evaristoc** [comment]
After few changes in the structure of the file the problem was solved. Taking the opportunity to thank you for working on this small wrapper.

**Comment by thisbejim** [comment]
Glad it all worked out @evaristoc!
