### ISSUE TITLE
special characters in child is skipped. for example db.child("+91") will be written to db as 91

### ISSUE THREAD

**Issue by sudheerkdty** [thisbejim/Pyrebase#187]
for example db.child("+91") will be written to db as 91.
the '+' symbol is skipped

**Comment by JooeunAhn** [comment]
use urllib.parse.quote_plus

quote_plus("+91")
'%2B91'

**Comment by sudheerkdty** [comment]
Your solution is for python3
for python 2 it is
urllib.pathname2url('+91')
