### ISSUE TITLE
stream.close() not working in python 2

### ISSUE THREAD

**Issue by harshil2712** [thisbejim/Pyrebase#188]
When I am using the stream.close() method, it is showing an error stating that this does not exist. I am using Python 2 for executing my code. Please suggest an alternative or a solution for this.

**Comment by thisbejim** [comment]
Hi @harshil2712 thanks for dropping by. Pyrebase does not support python2, I recommend switching to python3.

**Comment by codeAshu** [comment]
@harshil2712 Use this as a fix - https://gist.github.com/codeAshu/f6384203706e989b0d38db6e0a9d11e7
