### ISSUE TITLE
Using a stream in a docker container

### ISSUE THREAD

**Issue by simmeringc** [thisbejim/Pyrebase#215]
Hello,

I'm attempting to use a db stream inside a docker container. My stream outputs messages when run locally, but the stream handlers do no execute inside of a docker container. Do you think there's a port I need to expose to get streams to work in docker?

**Comment by simmeringc** [comment]
Fixed by running docker CMD with -u flag ex: python -u service.py

**Comment by beratuslu** [comment]
hello @simmeringc could you manage to work it stable?

I am running Pyrebase on docker on raspberry pi zero it just stops everything without giving an any exception...
