### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Tenzer** [thisbejim/Pyrebase#22]
Looking through the recent commits you made on the error handling of `.get()` (c393f845da9358d8a755a7ed9da1d1778df90830, 5b8a304e0ef05cda9264f81e741d4006b085ab86 and d4a83b887d9b26634d9f218caa35903220926dc2), I can't help but think if it wouldn't be more Pythonic to raise an exception in that case?

Having to check the returned output to see if it matches the data you expected to get back or if it's an error message, makes it a bit too much of a hassle in my mind.

From what I can tell, error statuses on the `.get()` method will either have to be due to not having enough access, or Firebase not being able to handle the request due to some unforeseen circumstances. Requesting a path that doesn't exist just returns status 200 and `null`, in which case Pyrebase will return `None` which matches what I would expect.

**Comment by thisbejim** [comment]
Thanks for the input (very helpful) and yeah you can tell I wasn't 100% what should be done there, I agree this is the right thing to do. Thoughts on https://github.com/thisbejim/Pyrebase/commit/c17ecf3fb2a05dcc0cfdb073f15bb1301cb51b83?

**Comment by Tenzer** [comment]
I actually think you can do it much easier, but just using the [`raise_for_status()`](http://docs.python-requests.org/en/latest/api/#requests.Response.raise_for_status) method on the response object from requests. It raises the error that has occurred as an exception for you :)

**Comment by Tenzer** [comment]
Oh sorry, I guess I'm a bit tired since I didn't notice that already is what you did. But what's the point then of making your own exception instead of just using the one it generates?

**Comment by thisbejim** [comment]
Yeah raise_for_status is neat! The extra exception is to get more info about what is going on, for example a 400 error could be a [couple of different things](https://www.firebase.com/docs/rest/guide/saving-data.html#section-rest-errors) so it helps to know as much about the issue as possible. I'm always forgetting to add indexes for complex queries so this will help me a lot!

**Comment by Tenzer** [comment]
I haven't done too much testing of what data you get in the exceptions directly from requests, so I'll trust this is the best way :)
