### ISSUE TITLE
Firestore support?

### ISSUE THREAD

**Issue by lohriialo** [thisbejim/Pyrebase#239]
Any plan to support Firestore anytime soon?

**Comment by thisbejim** [comment]
Firebase maintains an official python [Firestore library](https://googlecloudplatform.github.io/google-cloud-python/latest/firestore/index.html).

**Comment by LeonardoRick** [comment]
Is that possible to connect to the official python library using somthing like pyrebase does?

```
import pyrebase

config = {
  "apiKey": "apiKey",
  "authDomain": "projectId.firebaseapp.com",
  "databaseURL": "https://databaseName.firebaseio.com",
  "storageBucket": "projectId.appspot.com"
}

firebase = pyrebase.initialize_app(config)
```

**Comment by LeonardoRick** [comment]
@thisbejim firestore library is definetly a different approach. That is a server side library only...

**Comment by emrothenberg** [comment]
I forked and added firestore support. Usage is identical except you use "empyrebase" instead of "pyrebase":
emrothenberg/empyrebase

**Comment by emrothenberg** [comment]
I forked and added firestore support. Usage is identical except you use "empyrebase" instead of "pyrebase":
https://github.com/emrothenberg/empyrebase
