### ISSUE TITLE
Getting "Auth Token Expired" after one hour

### ISSUE THREAD

**Issue by jgv115** [thisbejim/Pyrebase#244]
I'm getting 

`  "error" : "Auth token is expired"` after an hour of being connected to the Firebase database.

I understand that Firebase has a 60 minute expiry on tokens but even when I run `auth.refresh(user['refreshToken'])` before the 60 minutes is up, at the 60 minute mark it will still come up with that error saying that my Auth token has expired.

Anyone know what's going on?

**Comment by vm06007** [comment]
did you manage to solve @jgv115 ??

**Comment by jgv115** [comment]
Yes I actually have. The problem was that I was running `auth.refresh()` in a different thread from the main thread. So my best guess is that the way I updated my `user` object was not thread safe and it led to the main thread's auth token not being updated for some reason.

If you are using threads in your script then make sure to use thread safe operations like queues etc to pass data between threads

**Comment by vm06007** [comment]
@jgv115 our code is very simple though, will this work?

firebase = pyrebase.initialize_app(config)
auth = firebase.auth()
user = auth.sign_in_with_email_and_password('bernardo_cdb@hotmail.com', 'typeriumbot335577@')
user = auth.refresh(user['refreshToken'])
userIdToken = user['idToken']
db = firebase.database()

**Comment by jgv115** [comment]
Looks good to me

**Comment by Rumidom** [comment]
is there an way to set the token expiration time? i just need it to be a little longer

**Comment by impsdc** [comment]
I do not understand the method refreshToken. What is the difference with just re-login the user? cause we need email and password for accessing to the auth method.

I mean we cant access user globally after login, so to use the refresh function we need to login again so why this function ?
