### ISSUE TITLE
Every time stream handler is called, it includes all items since start

### ISSUE THREAD

**Issue by AtpCats** [thisbejim/Pyrebase#26]
Hi there, 

When I'm streaming on a particular child I receive not only what was just added, but also the ones that were added before (all that were added while the stream was active). This happens when I use either push or set to add data.

Is this the expected behavior? Is it possible to listen to only new items?

Any help would be appreciated, thanks.

**Comment by thisbejim** [comment]
Hi @AtpCats, yeah it really shouldn't be doing this, just fixed with 7e5039305ed0ed8a0a0df72649e26c6faa7ac2ee 
Go ahead and download the newest version and be sure to check the slightly changed streaming docs.

**Comment by AtpCats** [comment]
Awesome, thanks for fixing it so fast. Also fixed another crash when removing items.

Glad I found an actively developed python lib for this.

**Comment by AtpCats** [comment]
Thanks for fixing it so fast! It also fixed a crash I had when removing items.

Glad I found an actively developed python lib for this.
