### ISSUE TITLE
#cx_frezze the 'gcloud' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by Medpy** [thisbejim/Pyrebase#271]
Make sure these boxes are checked before submitting your issue:

[] Check that your version of Python is 3.4+
[] Check that you are on the newest version of Pyrebase
[] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

**Comment by adityaradk** [comment]
I've ensured that all of the criteria in the response have been met. It still doesn't work.

After a lot of googling, I found out that cx_freeze and pyinstaller don't work with the `gcloud` module. They use the `google.cloud` module.

Is there any way to fix this?

**Comment by Medpy** [comment]
Search in python/site-package the gcloud folder and copy it and past in
folder of your application i found this solution and now i build many
application desktop with firebase
