### ISSUE TITLE
Consider using the GCloud Python Library for Storage

### ISSUE THREAD

**Issue by mcdonamp** [thisbejim/Pyrebase#28]
First off--this is awesome, and I'm amazed that you got this updated so quickly!

When you get a minute, I'd take a look at adding the [GCloud Python library](https://googlecloudplatform.github.io/gcloud-python/stable/storage-client.html), as it'll handle resumable uploads and downloads, and a bunch of other operations (list, etc.).

**Comment by thisbejim** [comment]
Thanks for the kind words! The GCloud library looks fantastic, I will definitely check it out.
