### ISSUE TITLE
Is there any way to log out a previously logged in user?

### ISSUE THREAD

**Issue by delCatta** [thisbejim/Pyrebase#284]
Im trying to add a sign out button on my flask proyect for people to change accounts...

**Comment by EstebanMontesinos** [comment]
auth.current_user = None not sure if this is secure but it works

**Comment by josueal1** [comment]
> auth.current_user = None not sure if this is secure but it works @EstebanMontesinos 

were you referring to `auth = firebase.auth()`  ?

**Comment by KamalPanara** [comment]
> auth.current_user = None not sure if this is secure but it works

it didn't work for me.
