### ISSUE TITLE
Authenticate with Firebase anonymously

### ISSUE THREAD

**Issue by chiboreache** [thisbejim/Pyrebase#298]
Hi!

Is it possible?

**Comment by cbenhagen** [comment]
No this is not possible at the moment. But it should be quite easy to add using this API:
https://firebase.google.com/docs/reference/rest/auth/#section-sign-in-anonymously

**Comment by chiboreache** [comment]
Oh, wow, really easy, already got it, thanks!

**Comment by cbenhagen** [comment]
Please open a pull request so others can use this as well. Thanks :)

chiboreache <notifications@github.com> schrieb am Do., 7. März 2019, 08:29:

**Comment by chiboreache** [comment]
Aw, I just get successful response with simple `https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=[my_API_KEY]`

But I just thinkering an entering counter for my Nuxt.js(Vue) site, so it's too hard for me to create some api logic

So, convert ugly js into coffeescript is a lot easier, so yeah, sorry for misleading you mate :)
