### ISSUE TITLE
Installation error with pycryptodome

### ISSUE THREAD

**Issue by sohilluhar** [thisbejim/Pyrebase#299]
Getting following error while trying to install:
 
Running setup.py install for pycryptodome ... error

Command "D:\Django\untitled\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\7R-0\\AppData\\Local\\Temp\\pip-install-_sg6ine7\\pycryptodome\\setup.py';f=getat
tr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\7R-0\AppData\Local\Temp\pip-record-wrkfvm
fc\install-record.txt --single-version-externally-managed --compile --install-headers D:\Django\untitled\venv\include\site\python3.7\pycryptodome" failed with error code 1 in C:\Users\7R-0\
AppData\Local\Temp\pip-install-_sg6ine7\pycryptodome\

**Comment by sachinsaju** [comment]
I was also having the same issue. I did the following and the issue was solved.

`pip3 install --upgrade setuptools`

`pip3 install --upgrade gcloud`

`pip3 install pyrebase`

Hope this works for all.

**Comment by sohilluhar** [comment]
@sachinsaju  I tried but didn't work
I am using pyrebase4 nwo 
work good for me

**Comment by asdFire** [comment]
What version of python are/were you using?

**Comment by sohilluhar** [comment]
@asdFire 3.7.2

**Comment by asdFire** [comment]
It works on 3.7.1, and I have had the same problem installing on any later version. Try 3.7.1

**Comment by abdelwahebmoalla** [comment]
please switch to https://github.com/nhorvath/Pyrebase4
it's a maintained version of pyrebase thanks to @nhorvath

**Comment by Abhishek01039** [comment]
I have installed pyrebase4.
it is installed successfully but when I try ```import pyrebase``` @abdelwahebmoalla  @sohilluhar 
then I am getting this error


``` import pyrebase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\11\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrebase\__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "C:\Users\11\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrebase\pyrebase.py", line 23, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto.PublicKey'```

**Comment by sohilluhar** [comment]
Check inside C:\Users\11\AppData\Local\Programs\Python\Python37-32\lib\site-packages 
make sure you have Crypto folder and PublicKey inside it.

**Comment by Abhishek01039** [comment]
yes Crypto folder has PublicKey folder @sohilluhar

**Comment by dade80vr** [comment]
same here

**Comment by Pushpajit** [comment]
You see the name of folder is 'crypto' not 'Crypto'. Rename the directory **crypto >> Crypto**  and you're done.

**Comment by msaumya23** [comment]
Command errored out with exit status 1: 'C:\Users\Asus\Desktop\facerecog\env\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Asus\\AppData\\Local\\Temp\\pip-install-gqpwf6u8\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\Asus\\AppData\\Local\\Temp\\pip-install-gqpwf6u8\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Asus\AppData\Local\Temp\pip-record-lrpr_sx5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Asus\Desktop\facerecog\env\include\site\python3.7\pycryptodome' Check the logs for full command output.

I'm getting this error. what to do

**Comment by nhorvath** [comment]
None of this error mentions any part of this project. Maybe open an issue
with pycryptodome.

**Comment by AbnasGaire** [comment]
Traceback (most recent call last):
  File "login.py", line 8, in <module>
    import pyrebase
  File "C:\Users\abnas\AppData\Local\Programs\Python\Python37\lib\site-packages\pyrebase\__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "C:\Users\abnas\AppData\Local\Programs\Python\Python37\lib\site-packages\pyrebase\pyrebase.py", line 23, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'

**Comment by AzDeveloper97** [comment]
try :

pip install pyrebase4
pip install pyrebase-t
pip install pycryptodome

it works for me. i'm using python3.8

**Comment by idkpranjal** [comment]
> try :
> 
> pip install pyrebase4
> pip install pyrebase-t
> pip install pycryptodome
> 
> it works for me. i'm using python3.8

no it didn't worked for me

**Comment by parthzile** [comment]
> Command errored out with exit status 1: 'C:\Users\Asus\Desktop\facerecog\env\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Asus\AppData\Local\Temp\pip-install-gqpwf6u8\pycryptodome\setup.py'"'"'; **file**='"'"'C:\Users\Asus\AppData\Local\Temp\pip-install-gqpwf6u8\pycryptodome\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Asus\AppData\Local\Temp\pip-record-lrpr_sx5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Asus\Desktop\facerecog\env\include\site\python3.7\pycryptodome' Check the logs for full command output.
> 
> I'm getting this error. what to do

I am facing the same issue

**Comment by MohammedAli-11** [comment]
line 17
    firebase = pyrebase.initialize_app(config) IndentationError: unexpected indent
    i am getting this error what should i do ?

**Comment by MohammedAli-11** [comment]
I am getting this error :( 
  ERROR: Command errored out with exit status 1: 'c:\users\aliha\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\aliha\\AppData\\Local\\Temp\\pip-install-m5bfr73_\\pycryptodome_d1e58210f07a49a1acb19300af62c053\\setup.py'"'"'; __file__='"'"'C:\\Users\\aliha\\AppData\\Local\\Temp\\pip-install-m5bfr73_\\pycryptodome_d1e58210f07a49a1acb19300af62c053\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\aliha\AppData\Local\Temp\pip-record-i8yryq2v\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\aliha\appdata\local\programs\python\python39\Include\pycryptodome' Check the logs for full command output.

**Comment by MohammedAli-11** [comment]
> .

not working for me

**Comment by Jay-devil** [comment]
> I was also having the same issue. I had this issue when installing pyrebase. I did the following and the issue was solved.
> 
> `pip3 install --upgrade setuptools`
> 
> `pip3 install --upgrade gcloud`
> 
> `pip3 install pyrebase`
> 
> Hope this works for all.

yes, very thanks bro

**Comment by akashdahad** [comment]
> I have installed pyrebase4.
> it is installed successfully but when I try `import pyrebase` @abdelwahebmoalla @sohilluhar
> then I am getting this error
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\11\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrebase\__init__.py", line 1, in <module>
>     from .pyrebase import initialize_app
>   File "C:\Users\11\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrebase\pyrebase.py", line 23, in <module>
>     from Crypto.PublicKey import RSA
> ModuleNotFoundError: No module named 'Crypto.PublicKey'```
> ```

Did You Find Solution for this?

**Comment by sohilluhar** [comment]
> > I have installed pyrebase4.
> > it is installed successfully but when I try `import pyrebase` @abdelwahebmoalla @sohilluhar
> > then I am getting this error
> > ```
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "C:\Users\11\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrebase\__init__.py", line 1, in <module>
> >     from .pyrebase import initialize_app
> >   File "C:\Users\11\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyrebase\pyrebase.py", line 23, in <module>
> >     from Crypto.PublicKey import RSA
> > ModuleNotFoundError: No module named 'Crypto.PublicKey'```
> > ```
> 
> Did You Find Solution for this?

Use pyrebase4

**Comment by AbdulConsole** [comment]
> You see the name of folder is 'crypto' not 'Crypto'. Rename the directory **crypto >> Crypto** and you're done.

Exactly... Worked for me... Thanks mahn

**Comment by CharanNK** [comment]
You can resolve it using the following steps:

First install pycryptodome:
`pip install pycryptodome`

and then run :
`pip install pyrebase`

**Comment by CodeWithVallabh** [comment]
Same with me. When I try to install pyrebase module in python, it shows an error that pycryptodome setup failed. Can anyone please help me to get out of this problem?

**Comment by CharanNK** [comment]
> Same with me. When I try to install pyrebase module in python, it shows an error that pycryptodome setup failed. Can anyone please help me to get out of this problem? 

You can resolve it using the following steps:

First install pycryptodome:
pip install pycryptodome

and then run :
pip install pyrebase

**Comment by ALIRAZA47** [comment]
> try :
> 
> pip install pyrebase4
> pip install pyrebase-t
> pip install pycryptodome
> 
> it works for me. i'm using python3.8

worked for me

**Comment by SumukhJadhav** [comment]
> please switch to https://github.com/nhorvath/Pyrebase4 it's a maintained version of pyrebase thanks to @nhorvath

This worked for me, thanks

**Comment by ghost** [comment]
Hello, 

Here is my code :

`
from ast import keyword
import tkinter 
from tkinter import *
import pyrebase

firebaseConfig={
    'apiKey': "",
    'authDomain': "",
    'projectId': "",
    'storageBucket': "",
    'messagingSenderId': "",
    'appId': "",
    'measurementId': ""
}

firebase=pyrebase.initialize_app(firebaseConfig)
auth=firebase.auth()

def signup():
    email=input("Enter email :")
    password=input("Enter password :")
    user=auth.create_user_with_email_and_password(email,password)

#Initialisation
root = tkinter.Tk()
root.geometry("1280x720")
root.maxsize(1280, 720)
root.minsize(1280, 720)
root.title("Launcher")
root.config(background='#2A2A2A')
`
#Fontions

def register_popup():
    popuproot = Toplevel(root)
    popuproot.title("Register")
    popuproot.geometry("400x600")
    popuproot.maxsize(400, 600)
    popuproot.minsize(400, 600)
    popuproot.config(background="#2A2A2A")
    
    #label
    
    text_popup_l = Label(popuproot, text="Register", font=("Candy Beans", 30), fg='white', bg='#2A2A2A')
    text_popup_l.place(x=120, y=30)

    username_text_popup_l = Label(popuproot, text="Username :", font=("Candy Beans", 15), fg='white', bg='#2A2A2A')
    username_text_popup_l.place(x=50, y=150)

    email_text_l = Label(popuproot, text="Email :", font=("Candy Beans", 15), fg='white', bg='#2A2A2A')
    email_text_l.place(x=50, y=230)

    password_text_l = Label(popuproot, text="Password :", font=("Candy Beans", 15), fg='white', bg='#2A2A2A')
    password_text_l.place(x=50, y=310)

    confirm_password_text_l = Label(popuproot, text="Confirm Password :", font=("Candy Beans", 15), fg='white', bg='#2A2A2A')
    confirm_password_text_l.place(x=50, y=390)
    
    #Entry
    
    username_popup_e = Entry(popuproot, relief=FLAT, width=45)
    username_popup_e.place(x=50, y=190)

    email_e = Entry(popuproot, relief=FLAT, width=45)
    email_e.place(x=50, y=270)

    password_e = Entry(popuproot, relief=FLAT, width=45)
    password_e.place(x=50, y=350)

    confirm_password_e = Entry(popuproot, relief=FLAT, width=45)
    confirm_password_e.place(x=50, y=430)
    
    #Button
    
    register_b = Button(popuproot, text="Register", font=("Candy Beans", 10), relief=FLAT, fg='white', bg='#00A6FF', width=37)
    register_b.place(x=50, y=490)
    
#label

text_l = Label(root, text="Login", font=("Candy Beans", 50), fg='white', bg='#2A2A2A')
text_l.place(x=560, y=120)

email_l = Label(root, text="Email :", font=("Candy Beans", 15), fg='white', bg='#2A2A2A')
email_l.place(x=458, y=260)

password_l = Label(root, text="Password :", font=("Candy Beans", 15), fg='white', bg='#2A2A2A')
password_l.place(x=458, y=340)

#Entry

username_b = Entry(root, relief=FLAT, width=60)
username_b.place(x=460, y=300)

email_b = Entry(root, relief=FLAT, width=60)
email_b.place(x=460, y=380)

#Button

register_b = Button(root, text="Register", font=("Candy Beans", 10), relief=FLAT, fg='#00A6FF', bg='#2A2A2A', command=register_popup)
register_b.place(x=1210, y=10)

login_b = Button(root, text="Login", font=("Candy Beans", 10), relief=FLAT, fg='white', bg='#00A6FF', width=50)
login_b.place(x=460, y=440)

#Loop
root.mainloop()
`

And when I run it it gives me this error  :

`
Traceback (most recent call last):
  File "d:\LixNew\Login\login.py", line 6, in <module>
    import pyrebase
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrebase\__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrebase\pyrebase.py", line 1, in <module>
    import requests
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py", line 63, in <module>
    from . import utils
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
PS D:\LixNew\Login> & C:/Users/LixNew/AppData/Local/Programs/Python/Python310/python.exe d:/LixNew/Login/login.py
Traceback (most recent call last):
  File "d:\LixNew\Login\login.py", line 6, in <module>
    import pyrebase
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrebase\__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrebase\pyrebase.py", line 1, in <module>
    import requests
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py", line 63, in <module>
    from . import utils
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "C:\Users\LixNew\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
PS D:\LixNew\Login> 
`

**Comment by unofficialdxnny** [comment]
You guys should definietly switch over to <a href="https://github.com/nhorvath/Pyrebase4">pyrebase4</a> if you havent already by now it is a better and maintained version of this library

**Comment by dmitryMalko** [comment]
> please switch to https://github.com/nhorvath/Pyrebase4 it's a maintained version of pyrebase thanks to @nhorvath

You are the best)) Thanks

**Comment by israr96418** [comment]
I m using "pip install pyrebase"
but it give me the above same error

change pyrebase to pyrbase4
it work for me , try this
pip install pyrebase4
