### ISSUE TITLE
Stream troubles

### ISSUE THREAD

**Issue by roykolak** [thisbejim/Pyrebase#30]
Hey there, I can't seem to get streaming to work.. My stream handler is never called. (I don't see logging in the handler) 

```python
def stream_handler(post):
	print(post)

my_stream = db.child("displays").stream(stream_handler, user['idToken'])
print(my_stream)
```

if I swap out the stream creation line with something more standard, it seems to work fine. 

```python
print(db.child("displays").get(user['idToken']).val())
```

I'm using this on a raspberry pi 2

**Comment by roykolak** [comment]
Using firebase 3 implementation

**Comment by thisbejim** [comment]
Hi there @roykolak! So I've just tested streaming on my end and everything seems to be working ok. Keep in mind that if you are trying to push data from the same program you have to wait until the stream is fully connected and listening (it can take a couple of seconds).

For example:
```
import time

def stream_handler(post):
    print(post)

my_stream = db.child("users").stream(stream_handler, user['idToken'])
time.sleep(10)
db.child("displays").push({"name": "morty"}, user['idToken'])
```

**Comment by roykolak** [comment]
man.. I feel like I'm messing up a small detail somewhere with sse and firebase...

So I listening for updates on

```python
db.child("displays").child("UNIQUE_ID").stream(stream_handler, None) 
```
(no auth is required for reading an individual display in my security rules and I'm using a version w/ the PR that you just merged from me)

I have the same `stream_handler` that you have above, it is just logging out the post. 

The way I'm testing is that I'm starting the stream listener and then changing the `state` prop (which is a big text blob) on the unique display id via the firebase.google.com admin interface. I'm never seeing any logging in my stream handler. Is this how you are testing?

**Comment by thisbejim** [comment]
Yep that's how I tested it earlier, for example:
```
def stream_handler(post):
    print(post)

my_stream = db.child("displays").child("1234").stream(stream_handler, None)
```

Here is what my db looks like:
![](http://i.imgur.com/tDwqAJ0.png)

Then I change it to: 
![](http://i.imgur.com/D951iYl.png)

And I get the following output in terminal:
![](http://i.imgur.com/9ety0dK.jpg)

Are you doing anything differently?

**Comment by roykolak** [comment]
That's exactly what I'm doing. Hmm.. I might try and use the SSEClient directly since I don't need a token for my resourse

**Comment by roykolak** [comment]
Ah! Figured it out.. I'm storing a large multi dimensional array (16x96) and it takes about 4/5 minutes to stream the initial state. I didn't realize that the initial state is streamed, will research the sseclient to see if that can be configured.

**Comment by roykolak** [comment]
New plan: upload my big chunks of nested json to Storage and stream the filename! Thanks for your help on this

**Comment by thisbejim** [comment]
I'm glad you found a solution :)

**Comment by joaquinmiguens** [comment]
Hey @thisbejim , I am working with pyrebase in my raspberry pi 3 and I have some troubles with streaming method. I have a couple of questions:
1- Can I retrieve user.uid from firebase in python? Because my database has these childs--> 'users/'+user.uid+'/../'. 
2- Can I listen for live changes with pyrebase? It has to be similar to child_changed method in javascript. Streaming method could work for it?

Thank you.

**Comment by tapas100** [comment]
can any one tell me how can i use order_by_child in streaming ?

**Comment by rawmean** [comment]
I have the same problem. I think the problem is that when the database has too many entries, stream doe not work. The stream callback is called when the db has only a few entries, but the callback is not called even once at the beginning when the db has ~2000 entries.

Is that expected?
