### ISSUE TITLE
closing streams

### ISSUE THREAD

**Issue by tinkerer** [thisbejim/Pyrebase#32]
self.resp.raw._fp.fp.raw._sock.shutdown(socket.SHUT_RDWR)
        self.resp.raw._fp.fp.raw._sock.close()

in the ssec.close function, resp.raw doesn't exist. I call my_stream.sse.resp.close() instead of my_stream.close() so that my application terminates correctly

**Comment by thisbejim** [comment]
Hi @tinkerer, Pyrebase is written for python 3, this error will only be raised when using python 2.

**Comment by codeAshu** [comment]
For python 2 use this https://gist.github.com/codeAshu/f6384203706e989b0d38db6e0a9d11e7
