### ISSUE TITLE
Pyrebase on Kivy

### ISSUE THREAD

**Issue by CoutinhoElias** [thisbejim/Pyrebase#381]
Problems when using pyrebase with kivy:

The android application opens and closes!

I have two theories:
1 - Or these imports are wrong:
a) from pyrebase import pyrebase
b) import pyrebase

I tested both and it only works on the computer.

2 - Or my requirement is incorrect regarding the yrebase:
requirements = python3, kivy == 2.0.0, https: //github.com/kivymd/KivyMD/archive/master.zip,pygments,sdl2_ttf==2.0.15,pillow, requests, certifi, urllib3, chardet, idna, plyer, peewee, pyrebase

Note: Without pyrebase and commenting on the functions I use pyrebase the system works.

**Comment by sanjayshreeyans** [comment]
According to this GitHub page, https://github.com/thisbejim/Pyrebase/issues/344
The requirements needed to be: python3==3.8.5,kivy==2.0.0rc4, kivymd==0.104.1,pyrebase,requests==2.21.0, urllib3, chardet, certifi, idna,gcloud,, oauth2client, requests-toolbelt, protobuf_cpp, python-jwt, pycryptodome, httplib2, pyparsing, pyasn1, pyasn1_modules, rsa,jwcrypto==0.8. Check if that works

**Comment by felipegerhardt** [comment]
After several days working on it, this requirements list worked for my Android 10:

requirements = python3,kivy==2.0.0,kivymd==0.104.1,mapview,pyrebase,geocoder,email-validator,requests,urllib3,chardet,idna,ratelim,decorator,click,dnspython,pillow,oauth2client,httplib2,pyparsing,pyasn1,pyasn1_modules,virtualenv,six,sh,rsa,requests-toolbelt,python-jwt,pygments,pycryptodome,ptyprocess,protobuf,platformdirs,pexpect,kivy-garden.mapview,kivy-garden,jws,googleapis-common-protos,gcloud,future,filelock,docutils,distlib,backports.entry-points-selectable,jwcrypto,cryptography,Deprecated,wrapt

**Comment by CoutinhoElias** [comment]
I got it too.
