### ISSUE TITLE
webapp2 not defined

### ISSUE THREAD

**Issue by maxbusko** [thisbejim/Pyrebase#39]
Google App Engine default project does not work after install Pyrebase
webapp2 not defined

**Comment by thisbejim** [comment]
There have been issues with Pyrebase installation for the past week (see #38). Try reinstalling Pyrebase, can you please let me know if that resolves your issue?

**Comment by maxbusko** [comment]
Hi @thisbejim, I tried several times.Every time I get an error "webapp2 not defined".

**Comment by thisbejim** [comment]
Pyrebase is not compatible with python2 and as far as I can tell [Google App Engine requires python2](http://stackoverflow.com/questions/24229203/does-google-app-engine-support-python-3).
