### ISSUE TITLE
Creating anonymous authentication accounts support

### ISSUE THREAD

**Issue by ghost** [thisbejim/Pyrebase#397]
can you add Creating anonymous authentication accounts support for the package
the package already awesome and will be better if we add anonymous  user that can read the data and the fire store

**Comment by DamenTheDev** [comment]
#398 For the time being, you can manually add it by following instructions in the Firebase documentation: https://firebase.google.com/docs/reference/rest/auth/#section-sign-in-anonymously

**Comment by ghost** [comment]
the `pyrebase4` package provide this
