### ISSUE TITLE
Bad request when creating a new user

### ISSUE THREAD

**Issue by sprite728** [thisbejim/Pyrebase#40]
Hello, 
I try to create a new user using the auth.create_user_with_email_and_password method. However, I ran into this error: `400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=....`

Can you offer some hints about how to solve this? Thanks

**Comment by thisbejim** [comment]
Thank you @sprite728 for helping improve Pyrebase, this is now fixed with 6b7cb21fbe5bdb857fe866391ff3c08fa96a55ba 

You can download the newest version of Pyrebase from pip now.
