### ISSUE TITLE
Missing Email When Not missing it

### ISSUE THREAD

**Issue by showierdata9978** [thisbejim/Pyrebase#407]
{
   "error":{
      "code":400,
      "message":"MISSING_EMAIL",
      "errors":[
         {
            "message":"MISSING_EMAIL",
            "domain":"global",
            "reason":"invalid"
         }
      ]
   }
})

`def SignUp(bottle,username,email = None,password = None):
        try:
            user = auth.create_user_with_email_and_password(email,password)
            auth.send_email_verification(user['idToken'])
            
            data = {
                 user['idToken']:{   
                    "name":username,
                    "idToken": user['idToken'],
                    "email":email
                 }
            }
            print(f'User made {data}')
            with open('users.json','w') as f:
                json.dump(data,f)
            return data,user
        except requests.HTTPError as e:
            ErrorHandler.check(e)
            `
Make sure these boxes are checked before submitting your issue:

[X] Check that your version of Python is 3.4+

[X] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.
Lost the last one but all checked 
Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

**Comment by ghost** [comment]
Close
