### ISSUE TITLE
Can't generate firebase key

### ISSUE THREAD

**Issue by 0rland0** [thisbejim/Pyrebase#41]
When I try to run the following code:
` config = {
    ...
}

firebase = pyrebase.initialize_app(config)
db = firebase.database()
print db.generate_key()`

I get the following error:
 

> Traceback (most recent call last):
>  File "myFilenName", line 14, in <module>
>     print db.generate_key()
>   File "/Users/dev/anaconda2/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 245, in generate_key
>     time_stamp_chars[i] = push_chars[now % 64]
> TypeError: string indices must be integers, not float

**Comment by thisbejim** [comment]
Hi @0rland0, thank you for raising your issue. Pyrebase is written for Python3 and will not work correctly with Python2, I recommend moving to Python3 in order to use Pyrebase.
