### ISSUE TITLE
How do we determine if Streaming stops?

### ISSUE THREAD

**Issue by nitinmeharia** [thisbejim/Pyrebase#42]
Hi, thanks for a great library. I would like to know how can we determine if there is a failure in Streaming service.
    
    my_stream = ref.child("posts").stream(stream_handler)
Since we initiate **my_stream** object & pass the data to the **stream_handler** method. But assume if **my_stream** stops calling this method (maybe if exception occurs on the thread). Then how can we determine that?

**Comment by thisbejim** [comment]
Hi @nitinmeharia, thanks for the question and sorry for the long response time!

So I am not 100% sure on the problem you are having - Did you discover any nice approaches to solve this problem? 

You could possibly use a try except in stream_handler:
```
def stream_handler(post):
    try:
        print(post["event"]) # put
        print(post["path"]) # /-K7yGTTEp7O549EzTYtI
        print(post["data"]) # {'title': 'Pyrebase', "body": "etc..."}
    except:
        print("error")
my_stream = db.child("posts").stream(stream_handler)
```
Is that what you mean? Please feel free to clarify as much as possible so I can help you out.

**Comment by tripliks** [comment]
Hi @thisbejim, I also have issue with streaming.

After a while streaming just stops. There are no received events. The thread is still there and everything seems to be working ok. Killing/restarting the thread helps.
