### ISSUE TITLE
Can't install it!

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [thisbejim/Pyrebase#426]
I can't install pyrebase in Python 3.9
error: 
      running build_ext
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycryptodome

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by AsifArmanRahman** [comment]
@Sayad-Uddin-Tahsin  you can consider to use [firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api) .

**Comment by IGN-Styly** [comment]
Try Reinstalling pip dowloading the dot PY from https://pip.pypa.io/en/stable/installation/

**Comment by Harishwarrior** [comment]
https://github.com/CSEKINGS/Pyrebase Use this fork as alternative
