### ISSUE TITLE
Firebase database missing token on set()

### ISSUE THREAD

**Issue by ipungg-junior** [thisbejim/Pyrebase#429]
TypeError: set() missing 1 required positional argument: 'token'

Db instance method set() work properly on localhost, but when deploy on heroku i got missing arg on method set().

What that mean?
Thanks.

**Comment by AsifArmanRahman** [comment]
@ipungg-junior Please check if you're using the same version of the package in local machine and heroku. There's probably mismatch among em.

<br>

If you find it helpful, please consider using [firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api) available in PyPI, which I recently started maintaining and adding new features as [pyrebase](https://github.com/thisbejim/Pyrebase) isn't maintained anymore.

**Thank you.**

**Comment by ipungg-junior** [comment]
i am back brotherrr, thanks a lot for your information :)
