### ISSUE TITLE
Stream not notified if data updated from script

### ISSUE THREAD

**Issue by UkiMiawz** [thisbejim/Pyrebase#43]
Hi,
Thank you for the great library, I'm currently using it for a personal garden project.
But I got a little bit of problem on the streaming part.

So in firebase, here's my database structure

![image](https://cloud.githubusercontent.com/assets/1776703/16714370/113c0072-46c1-11e6-976c-4380dd374f11.png)

And I start a stream to listening to changes from "light" key

```
firebase = pyrebase.initialize_app(config)
db = firebase.database()

def stream_handler(post):
    print "New post coming"
    print(post["event"])
    print(post["path"])    
    print(post["data"])

print "Listening to stream"
my_stream = db.child("fungi_automation").stream(stream_handler, None)
```
and I updated it from my other script to change the value
```
firebase = pyrebase.initialize_app(config)
db = firebase.database()

data = {
    "fungi_automation/light/": {
        "value": 1,
        "last_update": time.time()
    },
    "fungi_automation/water/": {
        "value": 1,
        "last_update": time.time()
    }
}

db.update(data)
```

But the stream doesn't notice the change. I already wait several seconds before submiting the update.

I tried to change the value directly from Firebase and my stream recognized it, I can see the changes on my console print. And push also works fine, I can also see the changes.

```db.child("fungi_automation").push({"name": "morty"}, None)```

but if I push with my own key, its not working
``` 
data = {"Morty": {"name": "Mortimer 'Morty' Smith"}}
db.child("fungi_automation").set(data) 
```

Did I do something wrong?

I also tried to update the value from my HTML front end using Firebase js, the value in the database was updated but the stream also didn't catch it.

Thank you for your time.

**Comment by thisbejim** [comment]
Hi @UkiMiawz, apologies for the long response time!

It looks like you might be using python2, is that correct?

**Comment by giladondon** [comment]
I am using python2 and having the same exact problem

**Comment by thisbejim** [comment]
Hi @giladondon, Python 2 is not supported which is why you are getting this issue.
