### ISSUE TITLE
The Current State of pyrabase [URGENT]

### ISSUE THREAD

**Issue by IGN-Styly** [thisbejim/Pyrebase#432]
Project Seems Inactive, I propose project transfer, maybe a fork or archiving.

**Comment by Lxstr** [comment]
This fork [https://github.com/josewails/Pirebase](https://github.com/josewails/Pirebase) uses [gcloud-auth](https://google-auth.readthedocs.io/en/latest/) for authentication in place of the deprecated Oauth2Client.

**Comment by Lxstr** [comment]
1. [Pyrebase4](https://github.com/nhorvath/Pyrebase4) seems to be maintained although still using Oauth2Client.
2. [Pirebase](https://github.com/josewails/Pirebase) using gcloud-auth
3. [Firebase-admin-python](https://github.com/firebase/firebase-admin-python) is new which has firestore, auth and sso support using firebase which uses google cloud APIs
