### ISSUE TITLE
Can't install it!

### ISSUE THREAD

**Issue by Prog-LucasAlves** [thisbejim/Pyrebase#434]
Make sure these boxes are checked before submitting your issue:

[x] Check that your version of Python is 3.4+
[x] Check that you are on the newest version of Pyrebase
[x] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

-----

Error message:

note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycryptodome

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by AsifArmanRahman** [comment]
You can consider installing [firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api) available in PyPI. @Prog-LucasAlves

**Comment by Prog-LucasAlves** [comment]
installing [firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api)

**Comment by Prog-LucasAlves** [comment]
installing [firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api)
