### ISSUE TITLE
How to set %DISPLAY NAME% using pyrebase ?

### ISSUE THREAD

**Issue by vikramsamak** [thisbejim/Pyrebase#436]
How to set display name of user while sign up process ? So it can be used during verification email sending procedure.

**Comment by AsifArmanRahman** [comment]
Unfortunately, the APIs of firebase doesn't allow setting username while signing up. It can be done after a user signs up (for creating an account with email and password). For signing in with gmail/FB the username is set as per that account name. You can use [firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api) for social login. @vikramsamak

**Comment by vikramsamak** [comment]
Thanks
