### ISSUE TITLE
i have this error when installing the module

### ISSUE THREAD

**Issue by zoroxide** [thisbejim/Pyrebase#437]
311\Crypto\SelfTest\Signature\test_vectors\PKCS1-PSS
      running build_ext
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycryptodome

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by AsifArmanRahman** [comment]
You can install [firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api). @loay-mohamed-xv
