### ISSUE TITLE
Cannot create a new user

### ISSUE THREAD

**Issue by scriptonist** [thisbejim/Pyrebase#44]
I am getting the following error on using the `create_user_with_email_and_password() `function

`400 Client Error: Bad Request for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=secret`

note: I am new to firebase

**Comment by rokf** [comment]
Did you use the `apiKey` as the secret?

**Comment by scriptonist** [comment]
@rokf Yeah ofcourse

**Comment by thisbejim** [comment]
Hi @scriptonist, have you enabled the Email/password provider in your Firebase dashboard under Auth -> Sign In Method?

**Comment by scriptonist** [comment]
@thisbejim Yeah i have enabled Email/password provider in your Firebase dashboard . Also note that i  am able to a add a user using firebase console and get the details of that user using the `sign_in_with_email_and_password(email, password)` Function.

**Comment by thisbejim** [comment]
Thanks for offering help, @rokf :smiley:

**Comment by thisbejim** [comment]
Okies, thanks for confirming that @scriptonist, can you please post your config (with identifying info redacted)? Will take a look at this tomorrow.

**Comment by scriptonist** [comment]
this is my config 
```
config = {
    "apiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "authDomain": "appname.firebaseapp.com",
    "databaseURL": "https://appname.firebaseio.com",
    "storageBucket": "appname.appspot.com",
}
```

thank you @thisbejim

**Comment by thisbejim** [comment]
Hi @scriptonist, first please make sure you are on the newest version of Pyrebase.

Second, make sure you are using python 3, not python 2.

Third, create a new file,run this simple script, and let me know what happens.:
```
import pyrebase

config = {
  "apiKey": "apiKey",
  "authDomain": "projectId.firebaseapp.com",
  "databaseURL": "https://databaseName.firebaseio.com",
  "storageBucket": "projectId.appspot.com"
}
firebase = pyrebase.initialize_app(config)
auth = firebase.auth()
user = auth.create_user_with_email_and_password("random@gmail.com", "crazy_password")
print(user)
```

**Comment by scriptonist** [comment]
@thisbejim The problem is solved now. I was able to add users to my app.I was using python3 and latest version of pyrebase. I was not able to  figure out how the problem happened and why the error crept it. 
Thank You for your Help @thisbejim

**Comment by thisbejim** [comment]
Good to hear, @scriptonist, happy coding!
