### ISSUE TITLE
legacy-install-failure  × Encountered error while trying to install package. ╰─> pycryptodome

### ISSUE THREAD

**Issue by rehan985** [thisbejim/Pyrebase#446]
I am facing this issue while installing the pyrebase using this command 
```

pip3 install pyrebase 

pip install pyrebase 

python3.10 pip install pyrebase
```

Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Running setup.py install for pycryptodome ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pycryptodome did not run successfully.
  │ exit code: 1
  ╰─> [361 lines of output]
      running install
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\Crypto

  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycryptodome

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by AsifArmanRahman** [comment]
Neither pyrebase or pyrebase4 support Python 3.10+.

<br>

You can use [firebase-rest-api](https://github.com/AsifArmanRahman/firebase-rest-api).

**Comment by rehan985** [comment]
yes ,It works for me .Thanks
