### ISSUE TITLE
Cannot pass a file object to the storage API (only a filename)

### ISSUE THREAD

**Issue by dutchmo** [thisbejim/Pyrebase#47]
The Storage.put() operation currently only handles file names, and then calls open() on the name.
It would be nice to pass a file object directly, to be able to handle something like werkzeug.datastructures.Filestorage.

My solution is to simply monkey-patch Storage by adding a new method almost the same as the put() method, but there may be a better way.
```

def monkeypatch_method(cls):
    def decorator(func):
        setattr(cls, func.__name__, func)
        return func
    return decorator

# INFO monkey patch to the pyrebase.Storage class
@monkeypatch_method(Storage)
def pyrebase_storage_put(self, file_object: FileStorage, token=None):
    # reset path
    path = self.path
    self.path = None
    if token:
        # file_object = open("requirements.txt", 'rb')
        request_ref = self.storage_bucket + "/o?name={0}".format(path)
        headers = {"Authorization": "Firebase " + token}
        print("file object: " + repr(file_object))
        request_object = self.requests.put(request_ref, headers=headers, data=file_object)
        print("JSON:" + repr(request_object.json()))
        return request_object.json()
    elif self.credentials:
        blob = self.bucket.blob(path)
    return blob.upload_from_filename(filename=file_object.filename)

def upload_file_to_firebase(image, resource_path):
    storage = get_firebase_app().storage()
    filepath = resource_path + image.filename
    storage.child(filepath).pyrebase_storage_put(image, token='Omye0DJUYHz...')
```

**Comment by thisbejim** [comment]
Potentially added support for this with 6bbce8faa364134968f4dbddfff03fd17fe5901b would you mind downloading the newest version of Pyrebase and testing it out? I'm not set up to test this at the moment.

You should just be able to do:
```
storage.child("images/example.jpg").put(your_file_storage_obj)
```

**Comment by dutchmo** [comment]
Works; I tested with both a BytesIO and a FileStorage object, as well as just a filename. (It doesn't work with a StringIO, which I think is normal, in any event the error from that doesn't come until the ssl layer).  Your library is useful, thanks!
