### ISSUE TITLE
Downloading Firebase Storage files?

### ISSUE THREAD

**Issue by avvemul** [thisbejim/Pyrebase#48]
Is there a way to do this yet?

**Comment by thisbejim** [comment]
Apologies for the super late reply @avvemul, this has not been implemented yet but thanks to you it is on my radar. Will get to it eventually!

**Comment by thisbejim** [comment]
Hi @avvemul, basic downloads with service accounts has been aded with 4a4ba6ee4814988dd06320067d602108684eb260
