### ISSUE TITLE
403 Permission denied

### ISSUE THREAD

**Issue by teodorgarzdin** [thisbejim/Pyrebase#49]
First off, I would like to say this is a great project!

Now onto the problem .. I have a Python application running on Google App Engine. 

**Python: 2.7.9.
Pyrebase: 3.0.7**

I'm using a service account to authenticate to Firebase. **I have anonymous and email and password authentication enabled.** The database rules are the default ones. I have cron jobs setup that run **once** each day and insert data into Firebase's database. Currently I get lots of **403 (Permission denied)** exceptions, when the cron jobs run. When I set the corn jobs to run more often, everything is fine (I had them running **2 hours apart** before).

So what would be causing this issue?

**Comment by thisbejim** [comment]
Hi @teodorgarzdin, thanks for the kind words! 

Unfortunately, Pyrebase does not support python2 so that is probably the issue.

**Comment by teodorgarzdin** [comment]
Thanks for the fast reply @thisbejim. Is it because Pyrebase is using the `requests` library to make requests?
