### ISSUE TITLE
For Firebase3 is there method we can use for signInWithCustomToken?

### ISSUE THREAD

**Issue by jayhuang75** [thisbejim/Pyrebase#50]
Hello,

Its such a good libs for build the middleware micro services. Good Job!

My question is, are you going to add the signInWithCustomToken method in the libs?

Thanks

**Comment by bazookon** [comment]
I use jose [https://github.com/mpdavis/python-jose](url) 

```
from jose import jwt
credencial = os.path.dirname(__file__) +'/firebase.json' #Your Firebase Json

def getCustomJWT(self,UID):
    data = None
    with open (credencial,'r') as file :
      data = json.loads(file.read());
    if data:
      t = int((datetime.now()).strftime('%s'))
      encoded = jwt.encode({
      'iss' : data['client_email'],
      'sub' : data['client_email'],
      'aud' : 'https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit',
      'iat' : t,
      'exp' : t+(60*60),
      'uid' : UID
      },data['private_key'],algorithm='RS256')
      return encoded
    else:
      return None
```

**Comment by thisbejim** [comment]
Thanks @bazookon, did that work for you @jayhuang75?

**Comment by erikcw** [comment]
This approach doesn't seem to work for me for REST api auth.

```
GET https://my-app.firebaseio.com/chats.json?auth={JWT_TOKEN} 

HTTP/1.1 400 Bad Request 
Content-Length: 54 
Content-Type: application/json; charset=utf-8 
Access-Control-Allow-Origin: * 
Cache-Control: no-cache 
Strict-Transport-Security: max-age=31556926; includeSubDomains; preload 
Connection: close 

{ 
"error" : "Missing claim 'kid' in auth header." 
} 
```

**Comment by jayhuang75** [comment]
@thisbejim Sorry, I dont have too much time for testing now. I will try lately.

**Comment by thisbejim** [comment]
Hi @jayhuang75, @bazookon, and @erikcw, create_custom_token and sign_in_with_custom_token methods have been added with e080f197a8a1b47a9a961d47d9b96ace0c29a96b

**Comment by jayhuang75** [comment]
Thats awesome.  Can't wait to try it out.                                                                                                                                                                        Sent from my BlackBerry                                                                                                                                                                                                                   From:notifications@github.comSent:August 24, 2016 9:44 PMTo:Pyrebase@noreply.github.comReply-to:reply@reply.github.comCc:jayhuang75@gmail.com; mention@noreply.github.comSubject:Re: [thisbejim/Pyrebase] For Firebase3 is there method we can use for signInWithCustomToken? (#50)  Hi @jayhuang75, @bazookon, and @erikcw, create_custom_token and sign_in_with_custom_token methods have been added with e080f19

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jayhuang75** [comment]
I confirm this new method is working great! And question: How can I catch the error and raise up to this method 
`auth.sign_in_with_custom_token(auth0_token)`
Thanks again!
