### ISSUE TITLE
using service account json file with heroku

### ISSUE THREAD

**Issue by nealrs** [thisbejim/Pyrebase#52]
Hola! Just wondering what the best practices are for using this library and the service account json file with a PaaS like Heroku. 

I figure it'd be a bad idea to commit the json file to git, so should I set all the json key pairs as env variables?

**Comment by thisbejim** [comment]
Hi @nealrs, I honestly have no idea what the best practice would be - but yes I'd recommend not pushing the json file to git. Sorry I couldn't be more help!

**Comment by markplindsay2** [comment]
This is a really old issue! But for anyone who might be searching for a solution to this problem, this is how I was able to authenticate using a service account with environment variables only:

```python
import os
import pyrebase

firebase = pyrebase.initialize_app({
    'apiKey': os.environ['FIREBASE_API_KEY'],
    'authDomain': os.environ['FIREBASE_AUTH_DOMAIN'],
    'databaseURL': os.environ['FIREBASE_DATABASE_URL'],
    'serviceAccount': {
        # Your "Service account ID," which looks like an email address.
        'client_email': os.environ['FIREBASE_CLIENT_EMAIL'], 
        # The part of your Firebase database URL before `firebaseio.com`. 
        # e.g. `fiery-flames-1234`
        'client_id': os.environ['FIREBASE_CLIENT_ID'],
        # The key itself, a long string with newlines, starting with 
        # `-----BEGIN PRIVATE KEY-----\n`
        'private_key': os.environ['FIREBASE_PRIVATE_KEY'].replace('\\n', '\n'),
        # Your service account "key ID." Mine is 40 alphanumeric characters.
        'private_key_id': os.environ['FIREBASE_PRIVATE_KEY_ID'],
        'type': 'service_account'
    },
    'storageBucket': ''
})
```

You'll see [here](https://github.com/thisbejim/Pyrebase/blob/2c152ae56f83bc653bf6204a3c9f68fa97b9d64a/pyrebase/pyrebase.py#L47-L50) that the `serviceAccount` config value is handled differently depending on if it is a `str` or `dict`.

AWS ECS, at least, is able to deal with environment variables of the length necessary to store the `FIREBASE_PRIVATE_KEY`.

**Comment by markplindsay** [comment]
This is a really old issue! But for anyone who might be searching for a solution to this problem, this is how I was able to authenticate using a service account with environment variables only:

```python
import os
import pyrebase

firebase = pyrebase.initialize_app({
    'apiKey': os.environ['FIREBASE_API_KEY'],
    'authDomain': os.environ['FIREBASE_AUTH_DOMAIN'],
    'databaseURL': os.environ['FIREBASE_DATABASE_URL'],
    'serviceAccount': {
        # Your "Service account ID," which looks like an email address.
        'client_email': os.environ['FIREBASE_CLIENT_EMAIL'], 
        # The part of your Firebase database URL before `firebaseio.com`. 
        # e.g. `fiery-flames-1234`
        'client_id': os.environ['FIREBASE_CLIENT_ID'],
        # The key itself, a long string with newlines, starting with 
        # `-----BEGIN PRIVATE KEY-----\n`
        'private_key': os.environ['FIREBASE_PRIVATE_KEY'].replace('\\n', '\n'),
        # Your service account "key ID." Mine is 40 alphanumeric characters.
        'private_key_id': os.environ['FIREBASE_PRIVATE_KEY_ID'],
        'type': 'service_account'
    },
    'storageBucket': ''
})
```

You'll see [here](https://github.com/thisbejim/Pyrebase/blob/2c152ae56f83bc653bf6204a3c9f68fa97b9d64a/pyrebase/pyrebase.py#L47-L50) that the `serviceAccount` config value is handled differently depending on if it is a `str` or `dict`.

AWS ECS, at least, is able to deal with environment variables of the length necessary to store the `FIREBASE_PRIVATE_KEY`.
