### ISSUE TITLE
Atomic Write and/or Check

### ISSUE THREAD

**Issue by newpro** [thisbejim/Pyrebase#55]
Hello!
Correct me if i am wrong. I can not use this lib to atomic write and/or check data.
For example, if I want to check if user/colin exists, and if not write to this location.

For firebase offical js library, it can be done by transaction function: https://www.firebase.com/docs/web/api/firebase/transaction.html

But here i have no way of lock the data when i check, and unlock it after i write.

Thanks! Keep up the good work :+1:

**Comment by thisbejim** [comment]
Hi @newpro, thanks for writing in!

That's right, Pyrebase does not support transactions (as much as I'd like to). Check out [this thread](http://stackoverflow.com/questions/23041800/firebase-transactions-via-rest-api) for how you can sort of emulate a transaction using security rules.

**Comment by newpro** [comment]
Thanks!
