### ISSUE TITLE
No naked child?

### ISSUE THREAD

**Issue by newpro** [thisbejim/Pyrebase#56]
First of all, that is a good title (I think :3)

It seems like the child method should not be used alone, for example:
```python
db.child('any_path')
db.child('some_good_path').get().val()
```
The first one will interfere with the second one.
I took a quick look i think it is because child function append path instead of set path
```python
if self.path:
    self.path += "/{}".format(new_path)
``` 

Correct me if i am wrong.
First, This issue does not allow store a reference to one location in db, because it will interfere with other queries. For example:

```python
ref = db.child('some_good_path_for_later')
print db.child('some_other_good_path').get().val()
```
Second,  if it is the design intention to not use child alone, should this function hide from users? e.g instead of doing

```python
db.child('path').get()
``` 

The child logic should be moved to the append functions, and use like this:

```python
db.get('path')
```

Thanks! Keep up the good work!

**Comment by thisbejim** [comment]
Hi @newpro, yeah this is a funny little quirk!

However, I'm comfortable with a little quirk like this if it means Pyrebase can have a familiar API for people coming from javascript.

One good way to store your refs though is to use a simple string, for example:
```
ref = 'some_good_path_for_later'
print db.child('some_other_good_path').get().val()
print db.child(ref).get().val()
```
These can even be multi-path, for example:
```
chatRef = 'chatrooms/4/users'
print db.child(chatRef).get().val()
```

**Comment by lsenta** [comment]
I have the same complaint:

It makes the use of the library prone to bugs, because code down the line can mess up the root `db` in an unpredictable way.

It's event more of a trap because it reads like idiomatic javascript chains but runs very differently:

```javascript
// Usual D3 code IIRC
var body = d3.select("body");
var h1 = body.append("h1");
var h2 = body.append("h2");

// Pyrebase
users = db.child("users")
a = users.child("john")
b = users.child("paul")
```

h2 points to `body h2`
b points to `users/john/paul`


Same thing for filtering, mutations are unexpected.

https://docs.djangoproject.com/en/1.10/topics/db/queries/#filtered-querysets-are-unique

Something like:
```python
class Database:
    ...
    @classmethod
    def _sub(cls, x, query=None, path=None):
        """Clone/Factory, naive implem, could use a Query object instead"""
        d = cls(x.credentials, ...)
        
        if path is not None:
            d.path = path 
        if query is not None:
            d.query = query
            
        return d

    def child(self, *path):
        suffix = "/".join([str(p) for p in path])

        if suffix.startswith("/"):
            suffix = suffix[1:]

        new_path = self.path + "/" + suffix

        return self._sub(self, path=new_path)

    def _with_query_param(self, name, value):
        return self._sub(self, query=dict(self.query, **{name: value}))

    def order_by_child(self, order):
        return self._with_query_param('orderBy', order)
    ...
```

would help.
