### ISSUE TITLE
Service Account and Stream

### ISSUE THREAD

**Issue by veled** [thisbejim/Pyrebase#58]
Thenk you for this beatiful library. It's very easy to use and smooth.

But I got a problem with stream.
My service account working smoothly if I get data with .get() method. But when I try to stream data with .stream() method, it gives me "permission denied" error. 

My service account get owner permission on firebase,
I'm working on Python 3.5.X
And I get the last version of Pyrebase.

**Comment by thisbejim** [comment]
Yeah this seems to be a bit of an issue. I just played around with getting this to work and was not successful. If we look at the [streaming documentation](https://firebase.google.com/docs/database/rest/retrieve-data) it looks like a stream might require the ```auth`` query parameter which we don't have when we are building a service account query (we use an authorisation header).

**Comment by godoppl** [comment]
Hi, and thank you for creating this library.

I ran into this same issue today. Are there any workarounds for this issue?

**Comment by thisbejim** [comment]
Hi @godoppl,

I'm glad you like the library. Unfortunately I haven't been able to solve this particular issue, I have asked for clarification on [firebasetalk](https://groups.google.com/forum/#!topic/firebase-talk/Rsb0lC9egN4) but have not gotten any responses yet.

**Comment by thisbejim** [comment]
So here is what is happening. 

We use [sseclient](https://bitbucket.org/btubbs/sseclient) for streaming which uses [requests](https://github.com/kennethreitz/requests) under the hood. All requests to the firebase REST API actually include a redirect and unfortunately the [requests package strips authorization headers on redirect](https://github.com/kennethreitz/requests/issues/2949), so when your service account query arrives it is no longer authorized.

**Comment by zbuttram** [comment]
Looks like there's a workaround in  kennethreitz/requests#2949, but that would have to be implemented in SSEClient

**Comment by rostopira** [comment]
same issue here(

**Comment by yuvadm** [comment]
Running into this problem as well. Attempting to stream with a service account gives me:

```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://s-usc1c-nss-117.firebaseio.com/test.json?ns=proj&sse=true
```

**Comment by lsenta** [comment]
@yuvadm have you tried passing the database secret (https://console.firebase.google.com/project/PROJECT/settings/database) to `stream(handler, token)`? It does the trick for me.

I found a solution without the need for auth token:
Pass the auth headers to the stream and use a custom session object that doesn't reset the auth on redirect.

https://github.com/thisbejim/Pyrebase/compare/master...lsenta:master

**Comment by wojtekw86** [comment]
I just had this problem with 'stream' and 401 error and found a solution here, but I think you should update your README.md on this project so others could have it clear right on start. And for the record - this lib is great!

**Comment by lsenta** [comment]
I'm glad this is still helpful!

Could you clarify your issue and how you solved it?
Where you using an old version of pyrebase and updated to fix the issue?
