### ISSUE TITLE
query chaining

### ISSUE THREAD

**Issue by thisbejim** [thisbejim/Pyrebase#6]
Right now queries are confusing and each method is a bit restrictive. Users should be able to build their own queries more explicitly, chaining a query together much like [complex queries](https://www.firebase.com/docs/web/guide/retrieving-data.html#section-complex-queries) in the javascript library. 
Example:
```python
results = admin.query("path/to/data").orderBy("votes").startAt(5).get()
```

**Comment by thisbejim** [comment]
[First pass attempted](https://github.com/thisbejim/Pyrebase/commit/e8e0de49021fa1d497e8cdb963ecac3c1d226439) but not thoroughly tested.

**Comment by Tenzer** [comment]
Do you plan on using `query()` for the POST, PUT, PATCH and DELETE requests as well? I guess there could be a minor problem in case users attempt to some of the lookup queries along with those actions, as Firebase don't support them. That could however be handled by either throwing an exception or silently discarding those options, with the benefit of having a similar interface for all operations.

**Comment by thisbejim** [comment]
I'm thinking the other four should stay separate, which makes sense if we can consider ```query().get()``` to be the missing GET method. 

Leading on from #10 (depending on what we decide), what do think about the names for the  POST, PUT, PATCH and DELETE methods? Should they match the js [saving data](https://www.firebase.com/docs/web/guide/saving-data.html) docs (set, update, push, remove)?

**Comment by Tenzer** [comment]
I am fine with the non-reading methods to be separate, and I think it would make sense to move away from the REST names, as this library is becoming less of a 1:1 mapping against the REST API, and rather a Python interpretation of the Javascript library. 
There is however have a slight problem with the current `get()` method, I have made #11 to track that.

**Comment by thisbejim** [comment]
Write methods have been updated to update, push, etc in f8711af2813d99d95921db2bde54396b90ddeb2b + might as well go the whole way so removed query() in favour of child() to more closely mirror the js library.
