### ISSUE TITLE
Streaming problem

### ISSUE THREAD

**Issue by t4kq1995** [thisbejim/Pyrebase#65]
Hello! I am trying to do Django/Python app and i want to use your library with Firebase database.
I try to stream some directory (my_stream = db.child("users").stream(stream_handler, user['idToken']))
and then i try to close stream (my_stream.close()) but i have an error:

self.sse.close()
AttributeError: 'NoneType' object has no attribute 'close'

I have a 3.4 python version, so can you help me with that?

**Comment by matt-erhart** [comment]
Same here.

**Comment by lsenta** [comment]
I got this issue writing tests, closing before the stream is fully initialized seem's to be an issue.
fix for me is to sleep before closing or wait for at least one trigger from the callback

**Comment by thisbejim** [comment]
Thanks for bringing up this issue @t4kq1995 and @matt-erhart and cheers for helping out @lsenta.

This has now been fixed with 46c13876bd76643ca355cf1d15eecc1866087b1b and will be in the next release.
