### ISSUE TITLE
Streaming Issues

### ISSUE THREAD

**Issue by Him-92** [thisbejim/Pyrebase#70]
Hey, 
I am on python 3.5 and have been trying to stream a database, however on executing the stream_handler nothing is printed. I am authenticated using a service account, but it doesn't even throw an unauthorized access error. What could be the problem. 

`def stream_handler(post):
    print(post["event"])
    print(post["path"])
    print(post["data"])'

my_stream=test_db.child("resources").stream(stream_handler)
`
# Prints Nothing

I understand that the handler is only supposed to act when there is a change made, but every time the streamer starts shouldn't it return the entire data under the child?
Also I tried putting random print statements in the handler function and even they weren't executed.

Thanks.

**Comment by lsenta** [comment]
Does it work when you `get().val()` the data?

I do get a None put on the simplest use case:

```
In [2]: x = db.child('sdkjl').stream(print)

In [3]: 2016-10-02 04:21:19,777 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): ...
2016-10-02 04:21:20,256 requests.packages.urllib3.connectionpool DEBUG    "GET /sdkjl.json HTTP/1.1" 307 0
2016-10-02 04:21:20,269 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): ....
2016-10-02 04:21:21,185 requests.packages.urllib3.connectionpool DEBUG    "GET /sdkjl.json?ns=...&sse=true HTTP/1.1" 200 None
{'path': '/', 'data': None, 'event': 'put'}
```

Enabling debug logging for the `requests` lib might help figure out if that's a broken configuration.

**Comment by thisbejim** [comment]
Hi @Him-92, try downloading the newest version of Pyrebase and giving this another go. Any changes?

**Comment by thisbejim** [comment]
I have tested streaming on python3.5 it is working fine, please feel free to let me know if you have any further issues.
