### ISSUE TITLE
Empty dictionaries are not stored in realtime database

### ISSUE THREAD

**Issue by ezcoding** [thisbejim/Pyrebase#71]
First of all I'd like to thank for this lib, it's a blast!

When adding/updating data through the `update` method, dictionaries without any keys won't be stored in firebase. Example:

`data = {'a': 'Hello', 'b': {}}`
`result = db.update(data, my_token)`

The dictionary `b` in `data` would never be stored in the database.

The absence of this dictionary compared to this dictionary without any keys and values, represent two very different things in my opinion. Any idea?

**Comment by thisbejim** [comment]
Hi @ezcoding, thanks for writing in!

Unfortunately this is how Firebase itself works (there's nothing Pyrebase can do about it) - it will not allow you to write empty dictionaries (or a null value) to the database. Not exactly sure why this is the case but I bet there is a good reason for it.

**Comment by ezcoding** [comment]
That's what I feared. It's strange though, that you can add empty JSON objects through the console.

Thanks anyway!
