### ISSUE TITLE
Stream throws JSONDecodeError

### ISSUE THREAD

**Issue by rostopira** [thisbejim/Pyrebase#80]
Streaming using service account throws exception from time to time (once for nearly 30-50minutes)

```
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 539, in start_stream
    msg_data = json.loads(msg.data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rostopira** [comment]
That was version 3.0.16
Testing with 3.0.17 now

**Comment by rostopira** [comment]
Seems to be fixed in 3.0.17, sry

**Comment by ddeath** [comment]
@thisbejim it looks like this is still a problem  got this exception multiple times...

I do not know what it causes because it happens randomly after some hours of streaming.

     Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/xxxxxx/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 556, in start_stream
        msg_data = json.loads(msg.data)
      File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Firebase 3.0.24, occurring during the streaming with service token

**Comment by busla** [comment]
I´m getting this error after exactly 3 hours. I tried to catch the exception in my code but for some reason I couldn´t.

Right now I´ve added an exception handler to _pyrebase.py_ to see if it works. Will report back in three hours.

**Comment by busla** [comment]
Ok, like a clock, 3 hours later, I could grab the exception.

`Unhandled Exception: credential is no longer valid`


```python
Unhandled Exception: credential is no longer valid
Traceback (most recent call last):
 File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 570, in start_stream
   msg_data = json.loads(msg.data)
 File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
   return _default_decoder.decode(s)
 File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
   raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by busla** [comment]
@thisbejim re-open?

**Comment by thisbejim** [comment]
Thanks for the details @bulsa, can you check if you are on the newest version of Pyrebase?

**Comment by thisbejim** [comment]
Oh nvm I just checked and I haven't pushed a change I thought I made which is in the stream handler and is something like:
if msg:
    msg_data = json.loads(msg.data)

Which basically avoids trying to load .data if msg doesn't exist. Good idea to reopen until this is added.

**Comment by busla** [comment]
@andreask1 seems that you´re using Python 3.4 and the `json` package might have changed between versions. I´m using 3.5.2

There is only a four line difference (357 vs 361) so they might have swapped out the `ValueError` for a more descriptive `JSONDecodeError`

**Comment by busla** [comment]
https://docs.python.org/3.4/library/json.html#json.JSONDecodeError
_If the data being deserialized is not a valid JSON document, a ValueError will be raised._

https://docs.python.org/3.5/library/json.html#json.JSONDecoder
_If the data being deserialized is not a valid JSON document, a JSONDecodeError will be raised._

**Comment by andreask1** [comment]
@busla Thank you for the clarification. I'll use Python 3.5 in my venv to get traces which are consistent with yours. Looks like streaming will need a little bit of work until it's reliable.

**Comment by busla** [comment]
What´s interesting is that after I handled the invalid credentials exception, it´s now being raised every 24 hours on the clock.

**Comment by busla** [comment]
Looks as if there are two separate issues here: An empty stream and invalid credentials.

**Comment by andreask1** [comment]
You mean this issue and #105? Not sure if they are directly connected ...

**Comment by busla** [comment]
No, that has been solved by automatically refreshing the token every 1 hour.

I´m getting `Unhandled Exception: credential is no longer valid` every 24 hours.

**Comment by andreask1** [comment]
@busla Do you need any help with testing of your fixes (which you could probably push to your forked repo)? I'm very interested in getting this issue resolved as it currently blocks my further implementation efforts.

**Comment by shamrin** [comment]
Here's my error, also during decoding (ValueError). Python 2.7, pyrebase==3.0.24.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/venv/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 556, in start_stream
    msg_data = json.loads(msg.data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by busla** [comment]
@andreask1 sure, will do it tomorrow morning.

**Comment by busla** [comment]
@andreask1 I don´t have my dev laptop with me but I made a simple exception so my code could continue to run:

https://github.com/busla/Pyrebase/commit/8145764c87504e3016543780ec1a676168613d56

**Comment by andreask1** [comment]
@busla Thanks, it's been working for me for 10 hours now, but I think this workaround only covers up a deeper problem with authentication.

The reason for the JSONDecodeError is that msg.data actually carries the following (non-json) text: "credential is no longer valid". So I think #105 is related and needs to be solved in order to solve this issue.

**Comment by andreask1** [comment]
@busla It was running ~24h with 20x JSONDecodeError suppressed by the workaround and 1x "403 Client Error: Forbidden for url" (#105). After that the stream ended with the following exception:
```python
<class 'requests.exceptions.HTTPError'>
502 Server Error: Bad Gateway for url: https://[...].firebaseio.com/[...]&sse=true
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/[...]/lib/python3.5/site-packages/sseclient/sseclient.py", line 81, in __next__
    nextchar = next(self.resp_iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/[...]/pyrebase3.py", line 556, in start_stream
    for msg in self.sse:
  File "/home/[...]/lib/python3.5/site-packages/sseclient/sseclient.py", line 85, in __next__
    self._connect()
  File "/home/[...]/pyrebase3.py", line 520, in _connect
    super(ClosableSSEClient, self)._connect()
  File "/home/[...]/lib/python3.5/site-packages/sseclient/sseclient.py", line 54, in _connect
    self.resp.raise_for_status()
  File "/home/[...]/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://[...].firebaseio.com/[...]&sse=true
```
Does this match yours (if you ignore the code lines as I edited pyrebase.py).

**Comment by busla** [comment]
@andreask1 in my case it happened after 12 hours. See #110

**Comment by thisbejim** [comment]
@busla @andreask1 @shamrin Thank you all for adding these details it will make it much easier to fix when I get some spare time.

**Comment by thisbejim** [comment]
@busla @andreask1 @shamrin I just cut a new version that hopefully addresses some of these issues (namely the ```json.loads(msg.data)``` error and the ```credential is no longer valid``` error). If any of you get the chance please give the new version a try, thanks! 😃

**Comment by busla** [comment]
@thisbejim thanks for putting effort into this 👍  I really appreciate it.

**Comment by andreask1** [comment]
@thisbejim Thanks, I appreciate it as well!
Streaming has been working well for a couple of hours now, but I will continue to test.
However, there is now a bug when closing the stream, but it should be easy to fix by just removing the now obsolate line "self.sse.thread.join()" in pyrebase.py:
```python
Traceback (most recent call last):
  File "[...]/main.py", line 115, in <module>
    time.sleep(2)
  File "[...]/main.py", line 105, in signal_handler
    fb_stream.close()
  File "/[...]/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 570, in close
    self.sse.thread.join()
AttributeError: 'ClosableSSEClient' object has no attribute 'thread'
```

**Comment by andreask1** [comment]
My test stream has been up and running for 1 1/2 days now without throwing an exception.

A minor downside of the current implementation is that with every reconnect the server resubmits the whole json tree monitored (every hour). Maybe it's possible to refresh the auth token (instead of waiting for expiration to reconnect or disconnecting/connecting periodically) to prevent this.

However, the current implementation works reliable and I would suggest to close this issue and also the related ones #105 and #110 after fixing the bug mentioned in my previous post.

**Comment by thisbejim** [comment]
Thanks for testing this out @andreask1, I really appreciate it 😃  

Yeah at the moment we wait for expiry then refresh the auth token and restart the stream. To be clear even the old way we had to restart the stream, you cannot reapply authentication to an open stream (I [looked into this](https://github.com/kennethreitz/requests/issues/3613) and it isn't possible). So in any implementation of refreshing the token we have to restart the stream. 

I am aware though that getting the whole tree a second time sucks and I have some ideas for how to avoid this in the future.

**Comment by thisbejim** [comment]
Will close this now with https://github.com/thisbejim/Pyrebase/issues/114 open.

**Comment by bulsa** [comment]
y am i receiving this? 
 

    On Monday, December 12, 2016 6:48 PM, James Childs-Maidment <notifications@github.com> wrote:
 

 Will close this now with #114 open.—

**Comment by thisbejim** [comment]
Looks like a slight name mix up between @bulsa and @busla, lol. 😄

**Comment by bulsa** [comment]
thk u.  

    On Tuesday, December 13, 2016 1:19 AM, James Childs-Maidment <notifications@github.com> wrote:
 

 Looks like a slight name mix up between @bulsa and @busla, lol. 😄 —

**Comment by busla** [comment]
😄

**Comment by busla** [comment]
Mine has been running for 3 days now without any hickups.

Good job!

**Comment by bulsa** [comment]
delete.  

    On Wednesday, December 14, 2016 6:17 PM, Jón Levy <notifications@github.com> wrote:
 

 Mine has been running for 3 days now without any hickups.Good job!—
