### ISSUE TITLE
Encoding issue with stream()

### ISSUE THREAD

**Issue by rostopira** [thisbejim/Pyrebase#81]
Cyrillic values retrieved from firebase is screwed up like this `ÐÐ¸Ð¼Ð° Ð¸Ð½ Ð´Ð° ÑÐ°ÑÑ`
Firebase uses UTF-8, as far as I know
Any workaround?
Latest version (3.0.17)

BTW, thank you, for all hard work you have done, it's really handy lib

**Comment by rostopira** [comment]
Found an workaround
https://github.com/LuminosoInsight/python-ftfy
```
from ftfy import fix_encoding
# ...
data = fix_encoding(even['data'])
```

**Comment by rostopira** [comment]
Data corrupted only when stream(). get() working OK

**Comment by rostopira** [comment]
Suddenly, encoding was WINDOWS-1251 0_o
Now, does anyone know, how set encoding to requests Session object?

**Comment by rostopira** [comment]
Encoding is probably WINDOWS-1251, but I'm not sure

**Comment by thisbejim** [comment]
Hi @rostopira, this looks to be a complex issue that is inherited from SSEClient which is the library that Pyrebase depends on for streaming. It isn't a great solution, but I do recommend handling any encoding issues on your end.
