### ISSUE TITLE
pip install Unicode decode error

### ISSUE THREAD

**Issue by ChadTeitsma** [thisbejim/Pyrebase#82]
I am getting the following error when trying to install the library using 'pip3 install pyrebase'. I previously used 'pip install pyrebase' but that downloaded it to python 2.7

chip@chip:~/Passageway$ pip3 install pyrebase
Downloading/unpacking pyrebase
  Downloading Pyrebase-3.0.18-py3-none-any.whl
Downloading/unpacking pycrypto (from pyrebase)
  Downloading pycrypto-2.6.1.tar.gz (446kB): 446kB downloaded
  Running setup.py (path:/tmp/pip-build-23zcdx76/pycrypto/setup.py) egg_info for package pycrypto

Downloading/unpacking python-jwt (from pyrebase)
  Downloading python_jwt-1.2.1-py2.py3-none-any.whl
Downloading/unpacking sseclient (from pyrebase)
  Downloading sseclient-0.0.12.tar.gz
  Running setup.py (path:/tmp/pip-build-23zcdx76/sseclient/setup.py) egg_info for package sseclient

Downloading/unpacking oauth2client (from pyrebase)
  Downloading oauth2client-3.0.0.tar.gz (77kB): 77kB downloaded
  Running setup.py (path:/tmp/pip-build-23zcdx76/oauth2client/setup.py) egg_info for package oauth2client

    warning: no previously-included files matching '*' found under directory 'tests'
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from pyrebase)
Downloading/unpacking gcloud (from pyrebase)
  Downloading gcloud-0.18.3.tar.gz (454kB): 454kB downloaded
  Running setup.py (path:/tmp/pip-build-23zcdx76/gcloud/setup.py) egg_info for package gcloud

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking requests-toolbelt (from pyrebase)
  Downloading requests_toolbelt-0.7.0-py2.py3-none-any.whl (52kB): 52kB downloaded
Downloading/unpacking jws>=0.1.3 (from python-jwt->pyrebase)
  Downloading jws-0.1.3.tar.gz
  Running setup.py (path:/tmp/pip-build-23zcdx76/jws/setup.py) egg_info for package jws
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-23zcdx76/jws/setup.py", line 17, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-build-23zcdx76/jws/setup.py", line 5, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 500: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-23zcdx76/jws/setup.py", line 17, in <module>

    long_description=read('README.md'),

  File "/tmp/pip-build-23zcdx76/jws/setup.py", line 5, in read

    return open(os.path.join(os.path.dirname(__file__), fname)).read()

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 500: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-23zcdx76/jws
Storing debug log for failure in /home/chip/.pip/pip.log

**Comment by ChadTeitsma** [comment]
This was done via Putty terminal on Windows. Running on the machine (we are using a CHIP) seemed to resolve the issue

**Comment by skunkwerk** [comment]
I am having the same issue trying to get pip to install JWS on AWS Elastic Beanstalk.  On Linux, not WIndows.

**Comment by ChadTeitsma** [comment]
@skunkwerk I had this issue again and it seemed to be because the Python encoding was not using UTF-8. I found this was due to me not having the 'locales' package installed. So I ran 'sudo apt-get install locales' and this installed the correct locales and Python was able to use UTF8 and I no longer received the error.

**Comment by alexandrahably** [comment]
I had the same error, but I could resolve it (on Raspberry Pi) by using:
sudo apt-get install locales
pip3 install jws

**Comment by mkoorn** [comment]
suffering the same issue, but I'm trying to install on a Synology Diskstation dsm4 where I don't have access to apt-get.
Any hints or tips?
