### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by kittiphanp** [thisbejim/Pyrebase#83]
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-ChPnww/pyrebase/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RWHGKW-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-ChPnww/pyrebase
Storing debug log for failure in /home/pi/.pip/pip.log

I got this error while installing, plz help

**Comment by thisbejim** [comment]
Hi @kittiphanp, are you using python2 or python3?

**Comment by kittiphanp** [comment]
Hi 
I am using python 3

Regards
KT

**Comment by thisbejim** [comment]
I recommend installing pyrebase in a fresh environment using [virtualenv](https://virtualenv.pypa.io/en/stable/installation/). You can find details on how to use virtualenv with python3 [here](http://stackoverflow.com/questions/23842713/using-python-3-in-virtualenv).

**Comment by kittiphanp** [comment]
Thanks a lot for your help .. Will figure out soon.
KT
