### ISSUE TITLE
ImportError: No module named http_client

### ISSUE THREAD

**Issue by EnriqueV** [thisbejim/Pyrebase#84]
Hello, I'm use Powerbase in my project, when config file with my credentials and trying run my script, i have this error:  

  File "/Library/Python/2.7/site-packages/gcloud/storage/blob.py", line 31, in <module>
    from gcloud._helpers import _rfc3339_to_datetime
  File "/Library/Python/2.7/site-packages/gcloud/_helpers.py", line 34, in <module>
    from six.moves.http_client import HTTPConnection
ImportError: No module named http_client

**Comment by thisbejim** [comment]
Hi @EnriqueV, pyrebase only works with python3 not python2.

**Comment by re2005** [comment]
Please mention that on README.ME and instructions?

**Comment by thisbejim** [comment]
It is literally the first thing in the readme after "getting started".

**Comment by re2005** [comment]
Oh man, u totally right, I'm sorry, I means the installation:

pip install pyrebase

to 

pip3 install pyrebase
