### ISSUE TITLE
Some setup errors

### ISSUE THREAD

**Issue by sbagri** [thisbejim/Pyrebase#88]
Hi

I see that pyrebase works for python2.7 also after I make a few modifications. Precisely speaking I verified only the reading, writing to firebase database part. Also I did 'pip install -r requirements.txt -t /someSpecificFolder' as this was needed for my work. So possibly if I remove the -t, the problem may be gone

I saw these errors for python2.7, I don't know if they are generic.
The errors are
1) No module named sseclient
Potential solution: possibly add sseclient in requirements.txt, as after I did 'pip install sseclient -t ./' the error was gone

2) ImportError: No module named google.protobuf
Potential solution: make an empty file __init__.py inside 'google' folder created while pip install ... -t ...

Thanks
Sharad

**Comment by thisbejim** [comment]
Hi @sbagri, thanks for writing in! However, I recommend forking and maintaining your own version of Pyrebase if you would like python2 compatibility.
