### ISSUE TITLE
Full ref in stream

### ISSUE THREAD

**Issue by busla** [thisbejim/Pyrebase#89]
Has full path to the ref in streams been removed in the latest update?

Before I updated I was splitting the post['path'] to get the tree I wanted:

`channels = post['path'].split('/')`

And then checking if certain items were in the list.

Now I only get the outermost ref but need the full path to make decisions on next action.

**Comment by busla** [comment]
Furthermore, I don´t receive data from Firebase unless I add a stream() to the outermost ref, instead of adding a stream to the root and receive data on any child update.

**Comment by busla** [comment]
If I http PUT data to my outermost child, instead of using pyrebase set(), I get the full path in the stream.

On this PUT, I get the full path in my stream function.

```
data = json.loads(mydatadict)
r = requests.put('http://myfirebaseurl/parent/child/data.json', data=data)
```

After posting the following I don´t receive the full path in my stream.

```
db.child('parent').child('child').set(data)

db.child('parent').child('child').update(data)

data = {'child': {'name': 'Busla'} }

db.child('parent').set(data)
```

**Comment by thisbejim** [comment]
Hi @busla, thanks for writing in! Pyrebase does not process the data that Firebase returns to a streaming connection in any way, so if there are any changes in data returned then I would say Firebase has made some changes internally.
