### ISSUE TITLE
use of Pycrypto

### ISSUE THREAD

**Issue by sankhakarfa** [thisbejim/Pyrebase#90]
Pycrypto installation is having some issue with python 3.5
Do you have any plans to shift from Pycrypto to other modules because it is not updated since 2014?

**Comment by thisbejim** [comment]
Hi @sankhakarfa, thanks for writing in! Any suggestions for a better maintained module?

**Comment by thisbejim** [comment]
This has been resolved with https://github.com/thisbejim/Pyrebase/commit/56aaa1dc38e83577a2d75c3377e864efe1ae0091
