### ISSUE TITLE
Download Url

### ISSUE THREAD

**Issue by sankhakarfa** [thisbejim/Pyrebase#91]
This is related to storage.
Hi the download url i am getting don't have token added to the end.
The url to download should be like this
`https://firebasestorage.googleapis.com/v0/b/blah blah-appspot.com/o/folder/video.mp4?alt=media&token=xxxxxxxx`
Can you show me how to add it or at least fetch it for a user who signs in/ authenticates using email and password?

Something similar to this. 
`# as user`
`storage.child("images/example.jpg").put("example2.jpg", user['idToken'])`

**Comment by thisbejim** [comment]
Hi @sankhakarfa, thanks for bringing this up! This should be supported with the ```.get_url(user['idToken'])``` method now which was added in https://github.com/thisbejim/Pyrebase/commit/f608d43d27b51d9ac72947fedc0493eccce0c581, please let me know if you have any issues after downloading the newest version.
