### ISSUE TITLE
Lock dependency versions in setup.py

### ISSUE THREAD

**Issue by stianjensen** [thisbejim/Pyrebase#92]
[x] Check that your version of Python is 3.4+
[x] Check that you are on the newest version of Pyrebase

Python_jwt released a new major version on the 26th of october, where they changed to name of the python module from jwt to python_jwt. This is great, because before there were lots of issues with naming collisions with pyjwt.

The problem however, is that in setup.py of pyrebase, no dependencies are locked to a specific version. So when install pyrebase now, jwt cannot load anymore, because version 2 of python_jwt is installed instead of version 1.2.1

One way to solve this is by specifying exact versions in setup.py just like is done in requirements.txt.
This is hard to maintain though, and an ideal solution would have this specified only one place.

A quick fix is to update the jwt import from

```
import jwt
```

to

```
import python_jwt as jwt
```

Although I really think something needs to be done to avoid future breakage when a major version of some package is released.

**Comment by thisbejim** [comment]
Thanks for letting me know @stianjensen, I didn't even realise the dependencies aren't locked so this is a big help, will make the change when I get the time.

**Comment by thisbejim** [comment]
Completed with https://github.com/thisbejim/Pyrebase/pull/93
