### ISSUE TITLE
Keep Firebase Keys Safe

### ISSUE THREAD

**Issue by MasterSwift** [thisbejim/Pyrebase#94]
How I keep my firebase configuration safe from public? Also, If I will be getting 1000+ requests to perform a python script and uploading data to firebase, isn't it unsafe to use the same key?

**Comment by thisbejim** [comment]
Hi @MasterSwift thanks for dropping by, can you please provide more details about your question?

**Comment by MasterSwift** [comment]
To configure firebase, I need to pass in the 5 parameters (api key, authdomain, databaseURL, storage bucket, service account path). Im running pyrebase on flask. Is it unsafe to have my firebase credentials inside one of the methods in my flask file?

**Comment by thisbejim** [comment]
It is safe to store everything but the service account json file in public view. 

The service account credentials should definitely be kept secret. If you are putting your project on github be sure to put your service account credentials json file in your .gitignore file so as to not expose the details to the internet. It is also recommended to store your credentials json file in an [environment variable](https://github.com/google/google-auth-library-ruby/issues/65#issuecomment-183665566).
