### ISSUE TITLE
Added a name property to distinguish between multiple streams

### ISSUE THREAD

**Issue by busla** [thisbejim/Pyrebase#95]
I´m using multiple streams so each instance of my class can listen to it´s on child ref. I needed to name the streams so I can identify them properly.

https://github.com/thisbejim/Pyrebase/compare/master...busla:master

Let me know if you think this is something you think is useful.

**Comment by thisbejim** [comment]
Thanks for bringing this up @busla! 

Yeah if this is something that you think would be useful then I am happy to include it.

The only changes I recommend is to make sure the ```name``` param comes last, for example:
```
def stream(self, stream_handler, name=None, token=None):
```
Should be:
```
def stream(self, stream_handler, token=None, name=None):
```

That way it doesn't break streaming for people who are already using tokens in that position.

And we should add an if statement in ```start_stream``` to only add the ```name``` if it is being used:
```
msg_data["name"] = name
```
Should be:
```
if name:
    msg_data["name"] = name
```

So feel free to make those changes, update the docs, and then make a PR!

**Comment by thisbejim** [comment]
Changed ```name``` to ```stream_id``` and added with https://github.com/thisbejim/Pyrebase/commit/b71999497ce4bdb0e06c13fc61234c6cc3506460, will be in next release.
