### ISSUE TITLE
Getting an attribute error when trying to download

### ISSUE THREAD

**Issue by Luminaii** [thisbejim/Pyrebase#96]
Hello,

When i'm trying to download a file '2.jpg' i'm getting the following error:
`Traceback (most recent call last):
  File "C:/Users/Luminai/Documents/CSN-PROG/HU-CSN-PROG-Project/test.py", line 10, in <module>
    storage.child("2.jpg").download("ftpwatch/1.jpg")
  File "C:\Users\Luminai\Miniproject\lib\site-packages\pyrebase\pyrebase.py", line 417, in download
    blob = self.bucket.get_blob(path)
AttributeError: 'Storage' object has no attribute 'bucket'`
I am also having this issues when trying to list all the files.

This is my code:

`import pyrebase
from auth import firebaseConfig as config
from auth import getFirebaseUser

firebase = pyrebase.initialize_app(config)

storage = firebase.storage()
#storage.child("4.jpg").put("sample/1.jpg",getFirebaseUser()['idToken'])
storage.child("2.jpg").download("ftpwatch/1.jpg")`

Uploading the file worked just fine but downloading is giving me issues.
I'm on python 3.5.2 and using Pyrebase 3.0.23

Kind Regards

**Comment by Luminaii** [comment]
Solved it. You have to use a service account.

**Comment by thisbejim** [comment]
Nice work solving this one @Luminaii! I've also added the ability to download storage files without a service account with https://github.com/thisbejim/Pyrebase/commit/ec78787b14449319bcc91f9cb08b9d7af22c981a however it is definitely recommended to use a service account.

**Comment by devil1993** [comment]
Does it work only with storage account? I tried it with a application account, it didn't work. 
https://stackoverflow.com/questions/48272023/unable-to-download-files-from-firebase-through-pyrebase
