### ISSUE TITLE
AttributeError: 'Storage' object has no attribute 'bucket'

### ISSUE THREAD

**Issue by bogdanr** [thisbejim/Pyrebase#97]
I have this bit of code in a file called `test.py`:
```python
import pyrebase

config = {
  "apiKey": "apiKey",
  "authDomain": "projectId.firebaseapp.com",
  "databaseURL": "https://blabla.firebaseio.com",
  "storageBucket": "blabla.appspot.com"
}

firebase = pyrebase.initialize_app(config)

storage = firebase.storage()
storage.child("public/giphy.gif").download("downloaded.gif")
```

And when I run `python test.py` I get this error:
```python
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    storage.child("public/giphy.gif").download("downloaded.gif")
  File "/root/crap/lib64/python3.5/site-packages/pyrebase/pyrebase.py", line 417, in download
    blob = self.bucket.get_blob(path)
AttributeError: 'Storage' object has no attribute 'bucket'
```
I installed Pyrebase-3.0.23 with pip and I am using Python 3.5.2.

**Comment by Luminaii** [comment]
Just figured this one out. You need to add a service account in the config. After that it will work.

**Comment by bogdanr** [comment]
Indeed, if I specify a valid service account it works. Nevertheless, that should be optional.

**Comment by thisbejim** [comment]
Thanks for bringing this up @bogdanr, this has been added in ec78787b14449319bcc91f9cb08b9d7af22c981a and will be in the next release.

**Comment by 19981999ab** [comment]
@bogdanr How did you add a service account?

**Comment by avj-jpg** [comment]
Was this feature ever added?

**Comment by avj-jpg** [comment]
storage.list_files() requires a service account. Can that be done with a service account as well?
