### ISSUE TITLE
apiKey should be optional if we use a serviceAccount

### ISSUE THREAD

**Issue by bogdanr** [thisbejim/Pyrebase#98]
Since right now it doesn't work with a service account it should not be necessary to specify the API key.
Nevertheless, if I don't do it I get the following error:
```python
    firebase = pyrebase.initialize_app(config)
  File "/root/crap/lib64/python3.5/site-packages/pyrebase/pyrebase.py", line 28, in initialize_app
    return Firebase(config)
  File "/root/crap/lib64/python3.5/site-packages/pyrebase/pyrebase.py", line 34, in __init__
    self.api_key = config["apiKey"]
KeyError: 'apiKey'
```

**Comment by thisbejim** [comment]
I still recommend including an apiKey with a service account as all the Auth methods still require the apiKey.
