### ISSUE TITLE
Is it possible to upload other kind of files apart from images to firebase storage using Pyrebase?

### ISSUE THREAD

**Issue by ParagRKadam** [thisbejim/Pyrebase#99]
I am trying to store .apk file to firebase storage  using the following code:-
```

storage = firebase.storage()
storage.child("apks/sample.apk").put("path/to/apk")
```

This stores the .apk file to firebase storage but when I try to download that file via firebase console and install the app on my android phone, it shows , Parse error - There is a problem parsing the package. I think the file is getting corrupt somehow. 
So my question is ,
Is this library meant to store just images to firebase storage or other files too ? And If other files too can be stored then how can it be done? Thanks.

**Comment by thisbejim** [comment]
Hi @ParagRKadam, thanks for writing in! I haven't tested other file types yet but yes my guess is in the current state Pyrebase probably only accepts images for Storage.

**Comment by ParagRKadam** [comment]
Can you please suggest if there is any way of storing other files to firebase storage using python?

**Comment by thisbejim** [comment]
I haven't got the slightest idea @ParagRKadam, I'll reopen this and take a look at it some time though.

In the mean time I recommend cloning Pyrebase and playing around with the [Storage put method](https://github.com/thisbejim/Pyrebase/blob/master/pyrebase/pyrebase.py#L383). Here is some additional information on [uploading file types to Firebase](https://firebase.google.com/docs/storage/web/upload-files).

**Comment by ParagRKadam** [comment]
Hey @thisbejim I got this to work. While I was uploading the .apk file to firebase storage I was changing its name before sending it which was causing the parse error ,upload the .apk file without changing the name worked for me. Thanks for the help and thanks for creating this awesome library.

**Comment by thisbejim** [comment]
That's great @ParagRKadam! Happy coding!
